package i18n

func init() {
	catalogs[En]["manage.update_review"] = "Update this node with the reviewed build? A pre-update backup is required by default; panel and VPN connections may pause."
	catalogs[Fa]["manage.update_review"] = "گره با نسخه بررسی‌شده به‌روز شود؟ به‌طور پیش‌فرض پشتیبان ساخته می‌شود؛ پنل و اتصال‌های VPN ممکن است قطع شوند."
	catalogs[En]["manage.core_installed"] = "Installed core / readiness"
	catalogs[Fa]["manage.core_installed"] = "هسته نصب‌شده و آمادگی"
	catalogs[En]["manage.core_recommended"] = "Recommended verified bundle"
	catalogs[Fa]["manage.core_recommended"] = "بسته تأییدشده پیشنهادی"
	catalogs[En]["manage.core_latest"] = "Latest compatible catalog entry"
	catalogs[Fa]["manage.core_latest"] = "آخرین بسته سازگار ثبت‌شده"
	catalogs[En]["manage.help"] = "\nTerminal management:\n  wg-guard manage [--lang fa|en]   Numbered host management menus\n  wg-guard                       Open management only on a TTY\n  wg-guard restart [--yes]        Locked, health-checked service restart\n  wg-guard install --lang fa      Persian setup wizard\n  Fresh --yes setup: --owner-username NAME --owner-password-file PRIVATE_FILE\n  Existing owner credentials are retained. Passwords never belong in argv.\n"
	catalogs[Fa]["manage.help"] = "\nمدیریت ترمینال:\n  wg-guard manage --lang fa\n  wg-guard restart --yes\n  wg-guard install --lang fa\n  نصب غیرتعاملی جدید: --owner-username NAME --owner-password-file PRIVATE_FILE\n  اطلاعات مالک موجود حفظ می‌شود؛ گذرواژه را در آرگومان قرار ندهید.\n"
	en := map[string]string{
		"manage.root": "Run on the host as root (sudo).", "manage.host": "Run management on the host, outside the container.", "manage.tty": "Interactive management needs a terminal. Use explicit commands and flags for automation.",
		"manage.subtitle": "VPN node · local management", "manage.build": "Build", "manage.installed": "Installed", "manage.absent": "No managed installation. Choose Setup / lifecycle to begin.", "manage.panel": "Panel access", "manage.endpoint": "Public VPN endpoint", "manage.health": "Health", "manage.healthy": "Responding", "manage.unhealthy": "Not responding; run status / doctor", "manage.core": "AmneziaWG bundle", "manage.reboot": "Core readiness: reboot required.", "manage.recovery": "Recovery required", "manage.journal": "Last lifecycle action", "manage.menu": "Management", "manage.lifecycle": "Setup / lifecycle", "manage.operations": "Operations / diagnostics", "manage.backups": "Backups / recovery", "manage.language": "فارسی / English",
		"manage.install": "Install a node", "manage.update": "Update WG-Guard", "manage.rollback": "Roll back to the previous build", "manage.recover": "Recover an interrupted update", "manage.uninstall": "Uninstall · preserve node data", "manage.status": "Status", "manage.doctor": "Doctor · read-only checks", "manage.tls": "Verify TLS certificate", "manage.switch": "Review / switch compatible core", "manage.restart": "Restart service", "manage.working": "Working… this may take a few minutes.", "manage.review": "Review impact",
		"manage.rollback_review": "Redeploy the previous healthy build? Compatibility and backup checks apply; connections may pause.", "manage.recover_review": "Recover the recorded lifecycle operation? Recovery uses the existing journal and may stop the service.", "manage.uninstall_review": "Remove the service, executable and managed configuration? Database, keys, backups and shared packages will be kept. Use CLI purge flags only for intentional data removal.", "manage.core_review": "Apply the catalogued core choice? Active VPN connections may be interrupted; unknown transitions are refused.", "manage.restart_review": "Restart the managed service? Panel and VPN connections may pause.",
		"manage.backup_create": "Create a backup", "manage.backup_list": "List backups", "manage.restore": "Restore an archive", "manage.schedules": "Add a daily schedule", "manage.telegram": "Telegram backups", "manage.backup_review": "Create an archive using current backup settings and configured delivery targets?", "manage.restore_boundary": "Restore uses the existing archive workflow. Coordinated lifecycle/database/key recovery is not yet available; do not use this to bypass a restore-required lifecycle journal.", "manage.archive": "Archive path", "manage.encrypted": "Is this archive password-encrypted?", "manage.password": "Archive password (hidden)", "manage.restore_review": "Review and restore this archive? Existing restore safeguards decide whether to apply offline or stage it; live activation needs a controlled restart.", "manage.schedule_boundary": "Daily schedule creation is available. Full list/edit/enable/delete management is being completed separately; use the panel for existing schedules.", "manage.time": "Daily time (UTC, HH:MM)", "manage.schedule_review": "Add this daily backup schedule? Retention and destinations use current backup settings.", "manage.telegram_test": "Send a test message", "manage.telegram_setup": "Configure token / chat", "manage.telegram_review": "Send a test message to the configured Telegram chat?", "manage.telegram_boundary": "Credentials are saved through shared settings. Delivery tests are explicit. Restart the service after editing settings to reload them.", "manage.token": "Telegram bot token (hidden)", "manage.chat": "Telegram chat ID (numeric)", "manage.telegram_save": "Save Telegram credentials to encrypted settings? No message will be sent.",
		"source.title": "Choose the build source", "source.latest": "Latest stable release", "source.list": "Published release list (up to 30)", "source.main": "Development · main", "source.sha": "Pinned development · full 40-character SHA", "source.empty": "No published stable release is available. Development must be selected explicitly.", "source.development": "Development build: source is pinned to the resolved immutable commit.", "source.confirm": "Use this build?",
	}
	fa := map[string]string{
		"manage.root": "روی میزبان با دسترسی root اجرا کنید (sudo).", "manage.host": "مدیریت را روی میزبان و بیرون از کانتینر اجرا کنید.", "manage.tty": "مدیریت تعاملی به ترمینال نیاز دارد. برای خودکارسازی از دستورها و گزینه‌ها استفاده کنید.",
		"manage.subtitle": "گره VPN · مدیریت محلی", "manage.build": "نسخه برنامه", "manage.installed": "نصب‌شده", "manage.absent": "نصب مدیریت‌شده‌ای یافت نشد. از بخش راه‌اندازی شروع کنید.", "manage.panel": "دسترسی پنل", "manage.endpoint": "نشانی عمومی VPN", "manage.health": "سلامت", "manage.healthy": "پاسخ‌گو", "manage.unhealthy": "پاسخ نمی‌دهد؛ status و doctor را اجرا کنید", "manage.core": "بسته AmneziaWG", "manage.reboot": "آمادگی هسته: راه‌اندازی مجدد میزبان لازم است.", "manage.recovery": "بازیابی لازم است", "manage.journal": "آخرین عملیات سرویس", "manage.menu": "مدیریت", "manage.lifecycle": "راه‌اندازی و نگهداری", "manage.operations": "عملیات و عیب‌یابی", "manage.backups": "پشتیبان و بازیابی", "manage.language": "فارسی / English",
		"manage.install": "نصب گره", "manage.update": "به‌روزرسانی WG-Guard", "manage.rollback": "بازگشت به نسخه قبلی", "manage.recover": "بازیابی به‌روزرسانی ناتمام", "manage.uninstall": "حذف سرویس · حفظ داده‌ها", "manage.status": "وضعیت", "manage.doctor": "عیب‌یابی · فقط بررسی", "manage.tls": "بررسی گواهی TLS", "manage.switch": "بررسی و تغییر هسته سازگار", "manage.restart": "راه‌اندازی مجدد سرویس", "manage.working": "در حال انجام… ممکن است چند دقیقه طول بکشد.", "manage.review": "بررسی اثر عملیات",
		"manage.rollback_review": "نسخه سالم قبلی اجرا شود؟ سازگاری و پشتیبان بررسی می‌شوند؛ اتصال‌ها ممکن است قطع شوند.", "manage.recover_review": "عملیات ثبت‌شده بازیابی شود؟ بازیابی از گزارش موجود استفاده می‌کند و ممکن است سرویس متوقف شود.", "manage.uninstall_review": "سرویس، برنامه و تنظیمات مدیریت‌شده حذف شوند؟ پایگاه داده، کلیدها، پشتیبان‌ها و بسته‌های مشترک حفظ می‌شوند. گزینه‌های purge فقط برای حذف عمدی داده هستند.", "manage.core_review": "هسته ثبت‌شده اعمال شود؟ اتصال‌های VPN ممکن است قطع شوند؛ تغییر ناشناخته پذیرفته نمی‌شود.", "manage.restart_review": "سرویس دوباره راه‌اندازی شود؟ پنل و اتصال‌های VPN ممکن است موقتاً قطع شوند.",
		"manage.backup_create": "ساخت پشتیبان", "manage.backup_list": "فهرست پشتیبان‌ها", "manage.restore": "بازیابی آرشیو", "manage.schedules": "افزودن برنامه روزانه", "manage.telegram": "پشتیبان تلگرام", "manage.backup_review": "آرشیو با تنظیمات و مقصدهای فعلی پشتیبان ساخته شود؟", "manage.restore_boundary": "بازیابی از روند فعلی آرشیو استفاده می‌کند. بازیابی هماهنگ چرخه سرویس، پایگاه داده و کلید هنوز آماده نیست؛ وضعیت restore-required را دور نزنید.", "manage.archive": "مسیر آرشیو", "manage.encrypted": "آیا آرشیو با گذرواژه رمزگذاری شده است؟", "manage.password": "گذرواژه آرشیو (مخفی)", "manage.restore_review": "آرشیو بررسی و بازیابی شود؟ حفاظت‌های موجود اجرای آفلاین یا آماده‌سازی را تعیین می‌کنند؛ فعال‌سازی به راه‌اندازی مجدد کنترل‌شده نیاز دارد.", "manage.schedule_boundary": "ساخت برنامه روزانه آماده است. مدیریت کامل فهرست، ویرایش، فعال‌سازی و حذف جداگانه تکمیل می‌شود؛ برای برنامه‌های موجود از پنل استفاده کنید.", "manage.time": "زمان روزانه (UTC، HH:MM)", "manage.schedule_review": "برنامه روزانه پشتیبان افزوده شود؟ نگهداری و مقصدها از تنظیمات فعلی گرفته می‌شوند.", "manage.telegram_test": "ارسال پیام آزمایشی", "manage.telegram_setup": "تنظیم توکن و گفت‌وگو", "manage.telegram_review": "پیام آزمایشی به گفت‌وگوی تلگرام تنظیم‌شده ارسال شود؟", "manage.telegram_boundary": "اطلاعات از تنظیمات مشترک ذخیره می‌شوند. آزمایش ارسال جداست. پس از تغییر تنظیمات سرویس را دوباره راه‌اندازی کنید.", "manage.token": "توکن ربات تلگرام (مخفی)", "manage.chat": "شناسه عددی گفت‌وگوی تلگرام", "manage.telegram_save": "اطلاعات تلگرام در تنظیمات رمزگذاری‌شده ذخیره شوند؟ پیامی ارسال نمی‌شود.",
		"source.title": "انتخاب منبع نسخه", "source.latest": "آخرین انتشار پایدار", "source.list": "فهرست انتشارها (حداکثر 30)", "source.main": "نسخه توسعه · main", "source.sha": "نسخه توسعه ثابت · SHA کامل 40 نویسه‌ای", "source.empty": "انتشار پایدار موجود نیست. نسخه توسعه را باید صریح انتخاب کنید.", "source.development": "نسخه توسعه: منبع به شناسه تغییرناپذیر ثبت‌شده متصل است.", "source.confirm": "از این نسخه استفاده شود؟",
	}
	for k, v := range en {
		catalogs[En][k] = v
	}
	for k, v := range fa {
		catalogs[Fa][k] = v
	}
}
