package i18n

func init() {
	catalogs[En]["setup.next"] = "Next: create the first interface (awg0) in the panel. Manage this node with wg-guard manage; diagnostics: wg-guard status / doctor."
	catalogs[Fa]["setup.next"] = "گام بعد: نخستین رابط (awg0) را در پنل بسازید. مدیریت گره: wg-guard manage؛ عیب‌یابی: wg-guard status / doctor."
	en := map[string]string{
		"intro": "Set up your VPN node. Enter keeps displayed defaults; back returns, q cancels.", "range": "Enter a number between %d and %d.", "mode": "Installation mode", "docker": "Docker · recommended, isolated control plane", "native": "Native · systemd service", "address": "Address / panel / TLS", "domain": "Panel domain (blank for IP-only access)", "ip": "Public VPN IP (blank detects a public address on this host)", "tls": "TLS mode", "proxy": "Reverse proxy · HTTP on loopback; proxy owns TLS", "dev": "Development · HTTP on loopback only", "acme": "Automatic certificate · ACME / Let's Encrypt", "manual": "Manual certificate · supply certificate and key files", "panel_port": "Panel TCP port", "http01": "HTTP-01 requires public TCP 80 to reach the challenge listener, including when its local port is customized.", "acme_port": "Local HTTP-01 TCP port", "cert": "TLS certificate file", "key": "TLS private-key file", "image": "Container image",
		"network": "VPN network defaults", "network_defaults": "Each AWG interface gets one UDP port in 30000–50000. Default pool: 10.8.0.0/24; MTU: 1420; DNS: 1.1.1.1, 1.0.0.1.", "custom_network": "Customize these defaults?", "port_min": "AWG UDP allocation range · start", "port_max": "AWG UDP allocation range · end", "port_order": "Range end must be greater than or equal to start.", "pool": "VPN subnet pool for the first interface", "cidr_invalid": "Enter a valid IPv4 CIDR, e.g. 10.8.0.0/24.", "mtu": "Client MTU", "dns": "Client DNS servers (comma-separated IPs)", "dns_invalid": "Every DNS entry must be an IP address.",
		"backup": "Optional backups", "telegram": "Configure Telegram delivery and a daily schedule now?", "token": "Telegram bot token (hidden)", "token_skipped": "No token entered; configure delivery later in Backups.", "chat": "Telegram chat ID (negative group IDs supported)", "chat_invalid": "Enter a nonzero numeric chat ID.", "time": "Daily backup time (UTC, HH:MM)", "time_invalid": "Enter HH:MM between 00:00 and 23:59.", "review": "Review installation", "panel": "Panel access URL", "endpoint": "Public VPN endpoint", "config": "Boot configuration", "data": "Data directory", "udp": "Per-interface AWG UDP allocation", "backup_set": "Chat %s · daily %s UTC", "backup_later": "Telegram is not configured; manage it later in Backups.", "impact": "Installation provisions prerequisites, writes managed configuration and starts the service. Existing unrelated resources are preserved.", "owner": "A local owner must be ready before the listener opens. Existing owner credentials are retained.", "proceed": "Proceed with installation?",
	}
	fa := map[string]string{
		"intro": "راه‌اندازی گره VPN. Enter مقدار پیشنهادی را نگه می‌دارد؛ back بازمی‌گردد و q لغو می‌کند.", "range": "عددی بین %d و %d وارد کنید.", "mode": "روش نصب", "docker": "Docker · پیشنهادی، محیط مدیریت جدا", "native": "نصب مستقیم · سرویس systemd", "address": "نشانی، پنل و TLS", "domain": "دامنه پنل (برای دسترسی با IP خالی بگذارید)", "ip": "IP عمومی VPN (خالی: شناسایی نشانی عمومی میزبان)", "tls": "روش TLS", "proxy": "پراکسی معکوس · HTTP محلی؛ TLS بر عهده پراکسی", "dev": "توسعه · HTTP فقط روی loopback", "acme": "گواهی خودکار · ACME / Let's Encrypt", "manual": "گواهی دستی · مسیر گواهی و کلید", "panel_port": "درگاه TCP پنل", "http01": "برای HTTP-01 باید TCP 80 عمومی به شنونده چالش برسد؛ حتی اگر درگاه محلی تغییر کند.", "acme_port": "درگاه TCP محلی HTTP-01", "cert": "فایل گواهی TLS", "key": "فایل کلید خصوصی TLS", "image": "تصویر کانتینر",
		"network": "پیش‌فرض‌های شبکه VPN", "network_defaults": "هر رابط AWG یک درگاه UDP در بازه 30000–50000 می‌گیرد. شبکه: 10.8.0.0/24؛ MTU: 1420؛ DNS: 1.1.1.1, 1.0.0.1.", "custom_network": "این پیش‌فرض‌ها تغییر کنند؟", "port_min": "بازه تخصیص UDP برای AWG · ابتدا", "port_max": "بازه تخصیص UDP برای AWG · انتها", "port_order": "انتهای بازه باید بزرگ‌تر یا برابر ابتدای آن باشد.", "pool": "شبکه VPN برای نخستین رابط", "cidr_invalid": "یک CIDR معتبر IPv4 وارد کنید؛ مانند 10.8.0.0/24.", "mtu": "MTU کاربر", "dns": "سرورهای DNS کاربر (IPها با ویرگول جدا شوند)", "dns_invalid": "هر مقدار DNS باید یک نشانی IP باشد.",
		"backup": "پشتیبان اختیاری", "telegram": "ارسال تلگرام و برنامه روزانه اکنون تنظیم شوند؟", "token": "توکن ربات تلگرام (مخفی)", "token_skipped": "توکنی وارد نشد؛ ارسال را بعداً در بخش پشتیبان تنظیم کنید.", "chat": "شناسه گفت‌وگوی تلگرام (شناسه منفی گروه پذیرفته می‌شود)", "chat_invalid": "شناسه عددی غیرصفر وارد کنید.", "time": "زمان روزانه پشتیبان (UTC، HH:MM)", "time_invalid": "زمان HH:MM بین 00:00 و 23:59 وارد کنید.", "review": "بررسی نصب", "panel": "نشانی دسترسی پنل", "endpoint": "نشانی عمومی VPN", "config": "تنظیمات راه‌اندازی", "data": "پوشه داده", "udp": "بازه تخصیص UDP هر رابط AWG", "backup_set": "گفت‌وگوی %s · روزانه %s UTC", "backup_later": "تلگرام تنظیم نشده است؛ بعداً از بخش پشتیبان مدیریت کنید.", "impact": "نصب، پیش‌نیازها و تنظیمات مدیریت‌شده را آماده و سرویس را شروع می‌کند. منابع نامرتبط موجود حفظ می‌شوند.", "owner": "پیش از شروع سرویس عمومی مالک محلی باید آماده باشد. اطلاعات ورود مالک موجود حفظ می‌شود.", "proceed": "نصب انجام شود؟",
	}
	for k, v := range en {
		catalogs[En]["setup."+k] = v
	}
	for k, v := range fa {
		catalogs[Fa]["setup."+k] = v
	}
}
