package i18n

func init() {
	rows := [][3]string{
		{"ops.action.update.canceled", "Maintenance request canceled", "درخواست نگهداری لغو شد"}, {"updates.prepared", "Version files are prepared", "فایل نسخه آماده است"},
		{"updates.copy_report", "Copy safe report", "کپی گزارش امن"},
		{"updates.failure.authorization_revoked", "The requesting account is disabled, missing or no longer allowed to manage updates.", "حساب درخواست‌کننده غیرفعال، حذف‌شده یا فاقد دسترسی مدیریت آپدیت است."},
		{"updates.browse_releases", "Browse published releases", "انتخاب از انتشارهای موجود"},
		{"ops.scope_help.update.read", "View component identity, operation history and recovery status; cannot run maintenance.", "مشاهدهٔ هویت اجزا، تاریخچهٔ عملیات و وضعیت بازیابی؛ بدون امکان اجرای نگهداری."},
		{"updates.snooze", "Remind me in 7 days", "یادآوری پس از ۷ روز"}, {"updates.catalog_rate_limit", "GitHub's request limit was reached. Retry is delayed; refresh will not bypass the limit.", "محدودیت درخواست GitHub رسیده است. تلاش دوباره با تأخیر انجام می‌شود؛ تازه‌سازی این محدودیت را دور نمی‌زند."},
		{"updates.failure.operation_failed", "The operation did not complete. Inspect the recorded stages.", "عملیات کامل نشد. مرحله‌های ثبت‌شده را بررسی کنید."}, {"updates.failure.broker_interrupted", "The host runner was interrupted; review recovery before retrying.", "اجرای میزبان قطع شده است؛ پیش از تلاش دوباره بازیابی را بررسی کنید."}, {"updates.failure.missed_window", "The maintenance window was missed; the operation was canceled.", "بازهٔ نگهداری گذشته است؛ عملیات لغو شد."}, {"updates.failure.acquisition_failed", "The selected build could not be acquired and verified.", "ساخت انتخاب‌شده دریافت و احراز نشد."}, {"updates.failure.preflight_blocked", "Readiness checks blocked the operation; review the failed checks.", "بررسی آمادگی عملیات را مسدود کرد؛ موارد ناموفق را بررسی کنید."}, {"updates.failure.backup_failed", "The required backup failed; deployment was not allowed to continue.", "بکاپ لازم ناموفق بود؛ ادامهٔ نصب مجاز نشد."}, {"updates.failure.health_failed", "The new panel did not pass health checks; inspect recovery.", "پنل جدید بررسی سلامت را پاس نکرد؛ بازیابی را بررسی کنید."}, {"updates.failure.core_failed", "Core maintenance failed; inspect the host observations.", "نگهداری هسته ناموفق بود؛ مشاهدات میزبان را بررسی کنید."}, {"updates.failure.reboot_required", "The new module is on disk; a planned host reboot is required.", "ماژول جدید روی دیسک است؛ reboot برنامه‌ریزی‌شدهٔ میزبان لازم است."}, {"updates.failure.recovery_failed", "Recovery is incomplete. Follow the dedicated recovery guide.", "بازیابی ناتمام است. راهنمای بازیابی مربوط را دنبال کنید."}, {"updates.failure.deployment_failed", "Deployment did not complete; inspect stages and recovery state.", "نصب کامل نشد؛ مرحله‌ها و وضعیت بازیابی را بررسی کنید."}, {"updates.failure.identity_changed", "The destination differs from the reviewed commit; select and check it again.", "مقصد با کامیت بررسی‌شده متفاوت است؛ دوباره انتخاب و بررسی کنید."},
		{"ops.scope.update.read", "View maintenance status", "مشاهدهٔ وضعیت نگهداری"},
		{"common.pagination", "Pagination", "صفحه‌بندی"},
		{"updates.workspace", "Node maintenance", "نگهداری نود"},
		{"updates.workspace_hint", "Review versions, prepare a change and follow its durable result.", "نسخه‌ها را بررسی کنید، تغییر را آماده کنید و نتیجهٔ ثبت‌شدهٔ آن را دنبال کنید."},
		{"updates.check_versions", "Check versions", "بررسی نسخه‌ها"},
		{"updates.sections", "Maintenance sections", "بخش‌های نگهداری"},
		{"updates.tab.overview", "Overview", "نمای کلی"}, {"updates.tab.versions", "Versions", "نسخه‌ها"}, {"updates.tab.operations", "Operations", "عملیات"}, {"updates.tab.recovery", "Recovery", "بازیابی"},
		{"updates.available", "An update is available", "به‌روزرسانی موجود است"}, {"updates.attention", "Maintenance needs attention", "نگهداری نیاز به توجه دارد"}, {"updates.last_check", "Last check", "آخرین بررسی"}, {"updates.review_versions", "Review changes", "بررسی تغییرات"},
		{"updates.manager", "Local manager", "مدیر محلی"}, {"updates.manager_hint", "Independent from the running panel", "مستقل از پنل در حال اجرا"}, {"updates.tools_hint", "Management tools; not the tunnel engine version", "ابزار مدیریت؛ نسخهٔ موتور تونل نیست"}, {"updates.bundle", "Recorded core bundle", "بستهٔ هستهٔ ثبت‌شده"}, {"updates.identity_unknown", "Identity has not been established", "هویت هنوز احراز نشده است"},
		{"updates.runtime", "Installed environment", "محیط نصب‌شده"}, {"updates.runtime_hint", "Host observations and configured tunnel backends", "مشاهدات میزبان و موتورهای تنظیم‌شدهٔ تونل"}, {"updates.inventory_missing", "No host inventory yet. Refresh observations using the host bridge.", "گزارش میزبان هنوز موجود نیست. مشاهدات را از طریق واسط میزبان تازه کنید."}, {"updates.inventory_stale", "These observations are over 15 minutes old; refresh before maintenance.", "این مشاهدات بیش از ۱۵ دقیقه قدمت دارند؛ پیش از نگهداری تازه‌سازی کنید."},
		{"updates.observed_at", "Observed", "زمان مشاهده"}, {"updates.mode", "Deployment", "روش نصب"}, {"updates.host", "Host", "میزبان"}, {"updates.kernel", "Host kernel", "کرنل میزبان"}, {"updates.module_identity", "Loaded module identity", "هویت ماژول فعال"}, {"updates.userspace", "Go engine", "موتور Go"}, {"updates.bridge", "Host bridge", "واسط میزبان"}, {"updates.backends", "Configured interfaces", "اینترفیس‌های تنظیم‌شده"},
		{"updates.identity.unknown", "Unknown", "نامشخص"}, {"updates.identity.matches-disk", "Loaded build matches disk", "ساخت فعال با دیسک یکسان است"}, {"updates.identity.differs-from-disk", "Loaded build differs from disk", "ساخت فعال با دیسک متفاوت است"},
		{"updates.userspace.unknown", "Not verified", "احراز نشده"}, {"updates.userspace.absent", "Not installed", "نصب نشده"}, {"updates.userspace.verified", "Reviewed build verified", "ساخت بازبینی‌شده احراز شد"},
		{"updates.bridge.unknown", "Not verified", "احراز نشده"}, {"updates.bridge.active", "Active at observation time", "فعال در زمان مشاهده"}, {"updates.bridge.inactive", "Inactive", "غیرفعال"},
		{"updates.build_details", "Build details", "جزئیات ساخت"}, {"updates.module_version", "Module reported version", "نسخهٔ گزارش‌شدهٔ ماژول"}, {"updates.tools_location", "Tools location", "محل ابزارها"}, {"updates.manager_commit", "Manager commit", "کامیت مدیر"}, {"updates.userspace_commit", "Go source commit", "کامیت سورس Go"}, {"updates.free_space", "Free data-volume space", "فضای آزاد محل داده"}, {"updates.inspect", "Refresh host observations", "تازه‌سازی مشاهدات میزبان"},
		{"updates.maintenance_rules", "Before you change versions", "پیش از تغییر نسخه"}, {"updates.rule.backup", "Panel upgrades create a local backup before deployment changes.", "ارتقای پنل پیش از تغییر نصب، بکاپ محلی می‌سازد."}, {"updates.rule.core", "Core changes use reviewed bundles. A host reboot may be required.", "تغییر هسته از بسته‌های بازبینی‌شده استفاده می‌کند. ممکن است reboot میزبان لازم باشد."}, {"updates.rule.reconnect", "Closing this page does not cancel a running host operation.", "بستن صفحه عملیات در حال اجرای میزبان را لغو نمی‌کند."}, {"updates.recovery_guide", "Recovery guide", "راهنمای بازیابی"},
		{"updates.component", "Component", "جزء نرم‌افزار"}, {"updates.search", "Filter version numbers", "فیلتر شمارهٔ نسخه"}, {"updates.per_page", "Per page", "در هر صفحه"}, {"updates.newer_only", "Newer than installed", "جدیدتر از نسخهٔ نصب‌شده"}, {"updates.clear_filters", "Clear filters", "پاک‌کردن فیلترها"}, {"updates.catalog_stale", "GitHub is unavailable. Showing the last successful result; execution revalidates the selection.", "GitHub در دسترس نیست. آخرین نتیجهٔ موفق نمایش داده می‌شود؛ انتخاب هنگام اجرا دوباره بررسی می‌شود."},
		{"updates.newer", "Newer", "جدیدتر"}, {"updates.older", "Older", "قدیمی‌تر"}, {"updates.details", "Details", "جزئیات"}, {"updates.no_matches", "No matching versions on this page", "نسخهٔ مطابقی در این صفحه نیست"}, {"updates.search_hint", "Filters apply to the retrieved page. Use next/previous for other published releases.", "فیلتر روی صفحهٔ دریافت‌شده اعمال می‌شود. برای انتشارهای دیگر از بعدی و قبلی استفاده کنید."}, {"updates.page_number", "Page %d", "صفحهٔ %d"}, {"updates.compact", "Compact view", "نمای فشرده"}, {"updates.recorded", "Recorded", "ثبت‌شده"},
		{"updates.selection", "Selected destination", "مقصد انتخاب‌شده"}, {"updates.choose_version", "Choose a version", "یک نسخه انتخاب کنید"}, {"updates.from", "Current", "فعلی"}, {"updates.to", "Destination", "مقصد"}, {"updates.downgrade_hint", "This is an older release. Execution checks compatibility; selecting it is different from restoring the retained previous artifact.", "این انتشار قدیمی‌تر است. اجرا سازگاری را بررسی می‌کند؛ انتخاب آن با بازگرداندن فایل قبلی نگهداری‌شده تفاوت دارد."}, {"updates.release_notes", "Release notes", "یادداشت انتشار"}, {"updates.notes_empty", "No release notes were provided.", "یادداشت انتشار ارائه نشده است."}, {"updates.open_release", "Open official release", "بازکردن انتشار رسمی"}, {"updates.core_change_hint", "The reviewed source bundle changes host module preparation. Active tunnels are not forcibly unloaded.", "بستهٔ سورس بازبینی‌شده آماده‌سازی ماژول میزبان را تغییر می‌دهد. تونل‌های فعال به‌اجبار unload نمی‌شوند."},
		{"updates.update_scope", "Components to update", "اجزای موردنظر"}, {"updates.scope.panel", "Manager and panel; keep current core", "مدیر و پنل؛ حفظ هستهٔ فعلی"}, {"updates.scope.all", "Manager, panel and recommended core", "مدیر، پنل و هستهٔ توصیه‌شده"}, {"updates.execution_hint", "Panel deployment briefly interrupts the web connection. A backup is created during execution.", "نصب پنل ارتباط وب را موقتاً قطع می‌کند. بکاپ هنگام اجرا ساخته می‌شود."}, {"updates.preflight", "Check readiness", "بررسی آمادگی"}, {"updates.prepare", "Prepare version files", "آماده‌سازی فایل نسخه"}, {"updates.schedule", "Maintenance window", "بازهٔ نگهداری"}, {"updates.schedule_at", "Run at (UTC)", "زمان اجرا (UTC)"}, {"updates.schedule_hint", "Choose 1 minute to 30 days ahead. An operation over 30 minutes late is canceled. No automatic reboot.", "از یک دقیقه تا ۳۰ روز آینده انتخاب کنید. عملیات با بیش از ۳۰ دقیقه تأخیر لغو می‌شود. reboot خودکار انجام نمی‌شود."}, {"updates.execute", "Confirm version change", "تأیید تغییر نسخه"}, {"updates.preflight_first", "Check this selection first. Readiness expires after 10 minutes and is checked again during execution.", "ابتدا همین انتخاب را بررسی کنید. آمادگی پس از ۱۰ دقیقه منقضی می‌شود و هنگام اجرا دوباره بررسی خواهد شد."}, {"updates.read_only", "Your account can view maintenance; execution needs a separate permission.", "حساب شما امکان مشاهده دارد؛ اجرا به دسترسی جداگانه نیاز دارد."},
		{"updates.confirm_selection", "Review the selected destination and components. The host runs a fresh preflight before changes; panel upgrades require a backup.", "مقصد و اجزای انتخاب‌شده را بررسی کنید. میزبان پیش از تغییرات بررسی تازه انجام می‌دهد؛ ارتقای پنل به بکاپ نیاز دارد."}, {"updates.enhanced_hint", "The installed host bridge predates detailed maintenance. Upgrade the manager/panel and repair the bridge to enable previews and scheduling.", "واسط نصب‌شده قدیمی‌تر از امکانات نگهداری جدید است. مدیر و پنل را ارتقا دهید و واسط را ترمیم کنید تا پیش‌بررسی و زمان‌بندی فعال شود."},
		{"updates.preflight_result", "Readiness result", "نتیجهٔ بررسی آمادگی"}, {"updates.preflight_limits", "Point-in-time checks require 2 GiB free space. Backup creation and service health are verified during execution; warnings are not proof of readiness.", "بررسی لحظه‌ای به ۲ GiB فضای آزاد نیاز دارد. ساخت بکاپ و سلامت سرویس هنگام اجرا بررسی می‌شوند؛ هشدارها اثبات آمادگی نیستند."}, {"updates.return_selection", "Return to selection", "بازگشت به انتخاب"},
		{"updates.check.platform", "Host platform", "پلتفرم میزبان"}, {"updates.check.journal", "Pending lifecycle operation", "عملیات نگهداری ناتمام"}, {"updates.check.disk", "Free staging/backup space", "فضای آزاد آماده‌سازی و بکاپ"}, {"updates.check.runtime", "Deployment tools", "ابزارهای نصب"}, {"updates.check.headers", "Running-kernel headers", "هدرهای کرنل فعال"}, {"updates.check.candidate", "Candidate contract", "قرارداد نسخهٔ مقصد"}, {"updates.check.data", "Artifact-only rollback compatibility", "سازگاری بازگشت فقط با فایل نرم‌افزار"}, {"updates.check.backup", "Backup will be created during execution", "بکاپ هنگام اجرا ساخته می‌شود"}, {"updates.check.module", "Loaded/disk module identity", "هویت ماژول فعال و دیسک"},
		{"updates.check_state.pass", "Passed", "موفق"}, {"updates.check_state.warn", "Review", "نیاز به بررسی"}, {"updates.check_state.fail", "Blocked", "مسدود"}, {"updates.check_state.unknown", "Unknown", "نامشخص"},
		{"updates.history", "Operation history", "تاریخچهٔ عملیات"}, {"updates.history_hint", "Up to 100 recent web maintenance operations; technical output stays private.", "تا ۱۰۰ عملیات اخیر نگهداری از وب؛ خروجی فنی خصوصی می‌ماند."}, {"updates.history_empty", "No completed operations yet", "هنوز عملیاتی پایان نیافته است"}, {"updates.requested_by", "Requested by", "درخواست‌کننده"}, {"updates.safe_report", "Download safe report", "دریافت گزارش امن"}, {"updates.cancel_request", "Cancel before start", "لغو پیش از شروع"}, {"updates.reconnecting", "The panel may be restarting. Reconnecting to the same operation; no new request is submitted.", "ممکن است پنل در حال راه‌اندازی مجدد باشد. اتصال به همان عملیات بررسی می‌شود؛ درخواست تازه‌ای ارسال نمی‌شود."},
		{"updates.state.scheduled", "Scheduled", "زمان‌بندی‌شده"}, {"updates.state.canceled", "Canceled", "لغوشده"}, {"updates.operation.inspect", "Host inspection", "بررسی میزبان"}, {"updates.operation.preflight", "Readiness check", "بررسی آمادگی"}, {"updates.operation.download", "Prepare version files", "آماده‌سازی فایل نسخه"}, {"updates.operation.rollback", "Restore previous artifact", "بازگرداندن فایل قبلی"}, {"updates.operation.recover", "Continue update recovery", "ادامهٔ بازیابی آپدیت"},
		{"updates.component.host", "Host", "میزبان"}, {"updates.component.manager", "Manager", "مدیر"}, {"updates.component.panel", "Panel", "پنل"}, {"updates.component.core", "Core", "هسته"}, {"updates.stage.inspect", "Inspect host", "بررسی میزبان"}, {"updates.stage.preflight", "Check readiness", "بررسی آمادگی"}, {"updates.stage.acquire", "Acquire verified build", "دریافت ساخت معتبر"}, {"updates.stage.verify", "Verify identity", "بررسی هویت"}, {"updates.stage.image", "Build Docker runtime", "ساخت محیط Docker"}, {"updates.stage.backup", "Create pre-update backup", "ساخت بکاپ پیش از آپدیت"}, {"updates.stage.deploy", "Deploy panel", "نصب پنل"}, {"updates.stage.health", "Check panel health", "بررسی سلامت پنل"}, {"updates.stage.manager", "Prepare manager", "آماده‌سازی مدیر"}, {"updates.stage.core", "Apply reviewed core", "اعمال هستهٔ بازبینی‌شده"}, {"updates.stage.recovery", "Recover previous deployment", "بازیابی نصب قبلی"}, {"updates.stage.complete", "Complete", "پایان"},
		{"updates.recovery_title", "Recovery and retained artifacts", "بازیابی و فایل‌های نگهداری‌شده"}, {"updates.recovery_hint", "Recovery follows the recorded lifecycle journal. Database restoration remains a host-side guided operation.", "بازیابی از journal ثبت‌شده پیروی می‌کند. بازگردانی پایگاه داده همچنان عملیات هدایت‌شدهٔ میزبان است."}, {"updates.no_recovery", "No pending recovery is recorded in the latest host observation.", "در آخرین مشاهدهٔ میزبان بازیابی ناتمامی ثبت نشده است."}, {"updates.reboot_required", "Host reboot required", "reboot میزبان لازم است"}, {"updates.reboot_hint", "Disk and loaded modules differ. Plan a host reboot, then inspect again. This page never reboots the host.", "ماژول دیسک و فعال متفاوت‌اند. reboot میزبان را برنامه‌ریزی و سپس دوباره بررسی کنید. این صفحه میزبان را reboot نمی‌کند."}, {"updates.recover_confirm", "Continue recorded update recovery. Other lifecycle operation types still require their dedicated host recovery command.", "بازیابی ثبت‌شدهٔ آپدیت ادامه می‌یابد. دیگر انواع عملیات نگهداری به فرمان بازیابی مخصوص خود در میزبان نیاز دارند."}, {"updates.rollback_confirm", "Restore the retained previous artifact only if its data contract is compatible. Current user data is not reset.", "فایل قبلی نگهداری‌شده فقط با قرارداد دادهٔ سازگار بازگردانده می‌شود. دادهٔ فعلی کاربران reset نمی‌شود."},
		{"updates.recovery_backup", "Pre-update backup", "بکاپ پیش از آپدیت"}, {"updates.backup_recorded_hint", "Recorded archive identity. Download verifies its SHA-256; this is not a successful restore drill.", "هویت آرشیو ثبت شده است. دریافت، SHA-256 آن را بررسی می‌کند؛ این به معنی تست موفق بازگردانی نیست."}, {"updates.encrypted", "Encrypted archive", "آرشیو رمزگذاری‌شده"}, {"updates.plaintext", "Unencrypted archive", "آرشیو بدون رمزگذاری"}, {"updates.download_backup", "Download recorded archive", "دریافت آرشیو ثبت‌شده"}, {"updates.backup_none", "No pre-update archive is referenced by the latest host journal.", "در آخرین journal میزبان ارجاعی به آرشیو پیش از آپدیت نیست."}, {"updates.backup_changed", "The archive no longer matches its recorded identity.", "آرشیو با هویت ثبت‌شده یکسان نیست."},
		{"updates.error.schedule", "Choose a valid UTC time between one minute and 30 days ahead.", "زمان معتبر UTC بین یک دقیقه و ۳۰ روز آینده انتخاب کنید."}, {"updates.error.cancel", "The request was already claimed or cannot be canceled.", "درخواست شروع شده یا قابل لغو نیست."},
	}
	for _, r := range rows {
		catalogEN[r[0]] = r[1]
		catalogFA[r[0]] = r[2]
	}
}
