package i18n

func init() {
	catalogs[En]["setup.next"] = "Next: sign in and create the first interface (awg0). Reopen this manager with sudo wg-guard; checks: sudo wg-guard status / doctor."
	catalogs[Fa]["setup.next"] = "گام بعد: نخستین رابط (awg0) را در پنل بسازید. مدیریت گره: wg-guard manage؛ عیب‌یابی: wg-guard status / doctor."
	en := map[string]string{
		"subtitle": "Secure AmneziaWG node setup", "intro": "Press Enter for the recommended choice; q cancels.", "range": "Enter a number between %d and %d.", "mode": "Installation mode", "docker": "Docker (recommended)", "native": "Native systemd", "address": "Connection", "access": "Panel access", "domain": "Panel domain (optional; Enter keeps access private)", "advanced": "Customize setup?", "recommended": "Recommended", "not_applicable": "Not applicable", "access_private": "Private · SSH tunnel", "access_direct": "Direct HTTPS", "access_nginx": "Managed Nginx HTTPS", "access_external-proxy": "External reverse proxy", "conflict": "Automatic public setup conflicts with an existing listener. Choose a safe access method below; WG-Guard will not stop or overwrite it.", "access_method": "Access method", "private": "Private via SSH tunnel (recommended)", "ip_https": "Public HTTPS on this server IP", "keep_recommended": "Keep the detected recommendation", "direct": "Direct HTTPS from WG-Guard", "managed_nginx": "Use standard host Nginx", "external_proxy": "Use an operator-managed reverse proxy", "certificate": "Certificate method", "cert_builtin": "Built-in automatic HTTPS", "cert_webroot": "Nginx shared webroot (recommended)", "cert_cloudflare": "Cloudflare DNS-01 · no validation port", "cert_manual": "Manual browser-trusted certificate files", "cert_origin": "Cloudflare Origin CA files · proxied hostname only", "cloudflare_token": "Scoped Cloudflare API token (hidden)", "cloudflare_invalid": "Enter a valid scoped Cloudflare API token.", "ip": "Public server IP", "tls": "TLS mode", "proxy": "Private HTTP on loopback (use an SSH tunnel or reverse proxy)", "dev": "Development HTTP on loopback", "acme": "Automatic HTTPS (recommended)", "manual": "Manual certificate files", "panel_port": "Panel TCP port", "https_port": "Direct HTTPS port", "backend_port": "Private loopback port", "public_https_port": "Public HTTPS port", "http01": "HTTP-01 validation requires public TCP 80; existing services are never stopped.", "acme_port": "Local HTTP-01 challenge port", "acme_email": "ACME account email (optional)", "cert": "TLS certificate file", "key": "TLS private-key file", "image": "Container image",
		"network": "VPN network defaults", "network_defaults": "Each AWG interface gets one UDP port in 30000–50000. Default pool: 10.8.0.0/24; MTU: 1420; DNS: 1.1.1.1, 1.0.0.1.", "custom_network": "Customize these defaults?", "port_min": "AWG UDP allocation range · start", "port_max": "AWG UDP allocation range · end", "port_order": "Range end must be greater than or equal to start.", "pool": "VPN subnet pool for the first interface", "cidr_invalid": "Enter a valid IPv4 CIDR, e.g. 10.8.0.0/24.", "mtu": "Client MTU", "dns": "Client DNS servers (comma-separated IPs)", "dns_invalid": "Every DNS entry must be an IP address.",
		"backup": "Optional backups", "telegram": "Configure Telegram backups now?", "token": "Telegram bot token (hidden)", "token_skipped": "No token entered. Configure Telegram later from Backups.", "chat": "Telegram chat ID", "chat_invalid": "Enter a nonzero numeric chat ID.", "time": "Daily backup time (UTC, HH:MM)", "time_invalid": "Enter HH:MM between 00:00 and 23:59.", "review": "Ready to install", "panel": "Panel", "endpoint": "VPN endpoint", "config": "Configuration", "data": "Data", "udp": "AWG UDP range", "backup_set": "Chat %s · daily %s UTC", "backup_later": "Telegram backups can be configured later.", "impact": "WG-Guard will install prerequisites, write its managed files, and start the node.", "owner": "A local owner must be ready before the listener opens. Existing owner credentials are retained.", "proceed": "Install WG-Guard?",
	}
	fa := map[string]string{
		"subtitle": "Secure AmneziaWG node setup", "intro": "راه‌اندازی گره VPN. Enter مقدار پیشنهادی را نگه می‌دارد؛ back بازمی‌گردد و q لغو می‌کند.", "range": "عددی بین %d و %d وارد کنید.", "mode": "روش نصب", "docker": "Docker · پیشنهادی، محیط مدیریت جدا", "native": "نصب مستقیم · سرویس systemd", "address": "نشانی، پنل و TLS", "access": "دسترسی پنل", "domain": "دامنه پنل (اختیاری)", "advanced": "Customize setup?", "recommended": "پیشنهادی", "not_applicable": "کاربرد ندارد", "access_private": "خصوصی با تونل SSH", "access_direct": "HTTPS مستقیم", "access_nginx": "HTTPS با Nginx مدیریت‌شده", "access_external-proxy": "پراکسی معکوس خارجی", "conflict": "راه‌اندازی عمومی خودکار با شنونده موجود تداخل دارد. یک روش امن انتخاب کنید؛ WG-Guard سرویسی را متوقف یا بازنویسی نمی‌کند.", "access_method": "روش دسترسی", "private": "خصوصی با تونل SSH (پیشنهادی)", "ip_https": "HTTPS عمومی روی IP سرور", "keep_recommended": "حفظ پیشنهاد شناسایی‌شده", "direct": "HTTPS مستقیم از WG-Guard", "managed_nginx": "استفاده از Nginx استاندارد میزبان", "external_proxy": "استفاده از پراکسی معکوس تحت مدیریت اپراتور", "certificate": "روش گواهی", "cert_builtin": "HTTPS خودکار داخلی", "cert_webroot": "مسیر مشترک Nginx (پیشنهادی)", "cert_cloudflare": "DNS-01 کلودفلر بدون پورت اعتبارسنجی", "cert_manual": "فایل‌های گواهی عمومی دستی", "cert_origin": "فایل Origin CA کلودفلر فقط برای دامنه پروکسی‌شده", "cloudflare_token": "توکن محدود API کلودفلر (مخفی)", "cloudflare_invalid": "توکن محدود معتبر کلودفلر را وارد کنید.", "ip": "IP عمومی سرور", "tls": "روش TLS", "proxy": "پراکسی معکوس · HTTP محلی؛ TLS بر عهده پراکسی", "dev": "توسعه · HTTP فقط روی loopback", "acme": "گواهی خودکار · ACME / Let's Encrypt", "manual": "گواهی دستی · مسیر گواهی و کلید", "panel_port": "درگاه TCP پنل", "https_port": "پورت HTTPS مستقیم", "backend_port": "پورت خصوصی loopback", "public_https_port": "پورت عمومی HTTPS", "http01": "اعتبارسنجی HTTP-01 به TCP 80 عمومی نیاز دارد و سرویس موجود متوقف نمی‌شود.", "acme_port": "پورت محلی چالش HTTP-01", "acme_email": "ایمیل حساب ACME (اختیاری)", "cert": "فایل گواهی TLS", "key": "فایل کلید خصوصی TLS", "image": "تصویر کانتینر",
		"network": "پیش‌فرض‌های شبکه VPN", "network_defaults": "هر رابط AWG یک درگاه UDP در بازه 30000–50000 می‌گیرد. شبکه: 10.8.0.0/24؛ MTU: 1420؛ DNS: 1.1.1.1, 1.0.0.1.", "custom_network": "این پیش‌فرض‌ها تغییر کنند؟", "port_min": "بازه تخصیص UDP برای AWG · ابتدا", "port_max": "بازه تخصیص UDP برای AWG · انتها", "port_order": "انتهای بازه باید بزرگ‌تر یا برابر ابتدای آن باشد.", "pool": "شبکه VPN برای نخستین رابط", "cidr_invalid": "یک CIDR معتبر IPv4 وارد کنید؛ مانند 10.8.0.0/24.", "mtu": "MTU کاربر", "dns": "سرورهای DNS کاربر (IPها با ویرگول جدا شوند)", "dns_invalid": "هر مقدار DNS باید یک نشانی IP باشد.",
		"backup": "پشتیبان اختیاری", "telegram": "ارسال تلگرام و برنامه روزانه اکنون تنظیم شوند؟", "token": "توکن ربات تلگرام (مخفی)", "token_skipped": "توکنی وارد نشد؛ ارسال را بعداً در بخش پشتیبان تنظیم کنید.", "chat": "شناسه گفت‌وگوی تلگرام (شناسه منفی گروه پذیرفته می‌شود)", "chat_invalid": "شناسه عددی غیرصفر وارد کنید.", "time": "زمان روزانه پشتیبان (UTC، HH:MM)", "time_invalid": "زمان HH:MM بین 00:00 و 23:59 وارد کنید.", "review": "بررسی نصب", "panel": "نشانی دسترسی پنل", "endpoint": "نشانی عمومی VPN", "config": "تنظیمات راه‌اندازی", "data": "پوشه داده", "udp": "بازه تخصیص UDP هر رابط AWG", "backup_set": "گفت‌وگوی %s · روزانه %s UTC", "backup_later": "تلگرام تنظیم نشده است؛ بعداً از بخش پشتیبان مدیریت کنید.", "impact": "نصب، پیش‌نیازها و تنظیمات مدیریت‌شده را آماده و سرویس را شروع می‌کند. منابع نامرتبط موجود حفظ می‌شوند.", "owner": "پیش از شروع سرویس عمومی مالک محلی باید آماده باشد. اطلاعات ورود مالک موجود حفظ می‌شود.", "proceed": "نصب انجام شود؟",
	}
	for k, v := range en {
		catalogs[En]["setup."+k] = v
	}
	for k, v := range fa {
		catalogs[Fa]["setup."+k] = v
	}
}
