package install

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"path/filepath"
	"time"

	"github.com/Sir-Adnan/wg-guard/internal/auth"
	"github.com/Sir-Adnan/wg-guard/internal/backup"
	"github.com/Sir-Adnan/wg-guard/internal/config"
	"github.com/Sir-Adnan/wg-guard/internal/database"
	"github.com/Sir-Adnan/wg-guard/internal/domainqueue"
	"github.com/Sir-Adnan/wg-guard/internal/domaintls"
	"github.com/Sir-Adnan/wg-guard/internal/layout"
)

const DomainBrokerServicePath = "/etc/systemd/system/wg-guard-domains.service"
const DomainBrokerPathPath = "/etc/systemd/system/wg-guard-domains.path"
const DomainBrokerTimerPath = "/etc/systemd/system/wg-guard-domains.timer"

func RenderDomainBrokerService() string {
	return `# Generated by wg-guard install
[Unit]
Description=WG-Guard approved domain and certificate operations
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/wg-guard domains request-run
TimeoutStartSec=20min
UMask=0077
`
}
func RenderDomainBrokerPath() string {
	return `# Generated by wg-guard install
[Path]
PathExists=/var/lib/wg-guard/domain-operations/request.json
Unit=wg-guard-domains.service
TriggerLimitIntervalSec=60
TriggerLimitBurst=2

[Install]
WantedBy=multi-user.target
`
}
func RenderDomainBrokerTimer() string {
	return `# Generated by wg-guard install
[Timer]
OnBootSec=3min
OnUnitInactiveSec=12h
RandomizedDelaySec=10min
Unit=wg-guard-domains.service

[Install]
WantedBy=timers.target
`
}

func EnsureDomainBroker(ctx context.Context, h Host) error {
	if !h.IsRoot() {
		return terminalError("manage.root")
	}
	q := domainqueue.New(DataDir)
	if err := h.MkdirAll(q.Dir, 0700); err != nil {
		return err
	}
	if err := ensureDomainDirectories(h); err != nil {
		return err
	}
	files := []struct{ path, content string }{{DomainBrokerServicePath, RenderDomainBrokerService()}, {DomainBrokerPathPath, RenderDomainBrokerPath()}, {DomainBrokerTimerPath, RenderDomainBrokerTimer()}}
	for _, file := range files {
		previous, err := captureFile(h, file.path, 64<<10)
		if err != nil {
			return err
		}
		if previous.exists && string(previous.data) != file.content {
			return fmt.Errorf("domains: host bridge file is unowned or changed")
		}
	}
	for _, file := range files {
		if err := atomicWrite(h, file.path, []byte(file.content), 0644); err != nil {
			return err
		}
	}
	if err := runQuiet(ctx, h, []string{"systemctl", "daemon-reload"}, 30*time.Second); err != nil {
		return err
	}
	if err := runQuiet(ctx, h, []string{"systemctl", "enable", "--now", "wg-guard-domains.path", "wg-guard-domains.timer"}, time.Minute); err != nil {
		return err
	}
	if err := atomicWrite(h, q.File("broker.json"), []byte("{\"schema\":1}\n"), 0600); err != nil {
		return err
	}
	if st, _ := LoadState(h); st != nil {
		return PublishDomainInventory(ctx, h)
	}
	return nil
}

func ensureDomainDirectories(h Host) error {
	for _, dir := range []string{layout.DomainDir, layout.DomainChallenges} {
		if err := h.MkdirAll(dir, 0700); err != nil {
			return err
		}
		if _, real := h.(realHost); real {
			info, err := h.Stat(dir)
			if err != nil || !info.IsDir() || info.Mode().Perm() != 0700 {
				return fmt.Errorf("domains: managed directories must be root-private")
			}
		}
	}
	return nil
}

func EnsureDomainBrokerForContract(ctx context.Context, h Host, c Contract) error {
	if c.DomainProtocol == 1 {
		return EnsureDomainBroker(ctx, h)
	}
	if c.DomainProtocol != 0 {
		return terminalError("install.error.contract")
	}
	if err := checkDomainRuntimeCompatibility(h, c); err != nil {
		return err
	}
	files, err := StopDomainBroker(ctx, h)
	if err != nil {
		return err
	}
	for _, file := range files {
		if err := h.Remove(file); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
	}
	if len(files) > 0 {
		return runQuiet(ctx, h, []string{"systemctl", "daemon-reload"}, 30*time.Second)
	}
	return nil
}

func RepairDomainBroker(ctx context.Context, h Host) error {
	if !h.IsRoot() {
		return terminalError("manage.root")
	}
	unlock, err := h.LockLifecycle()
	if err != nil {
		return err
	}
	defer unlock()
	if err := noPending(h); err != nil {
		return err
	}
	st, err := LoadState(h)
	if err != nil || st == nil || st.Current == nil || st.Current.Contract.DomainProtocol != 1 {
		return fmt.Errorf("domains: compatible installed runtime is required")
	}
	return EnsureDomainBroker(ctx, h)
}

func PublishDomainInventory(ctx context.Context, h Host) error {
	i, err := DomainStatus(ctx, h)
	if err != nil {
		return err
	}
	raw, err := json.Marshal(i)
	if err != nil {
		return err
	}
	return atomicWrite(h, domainqueue.New(DataDir).File("inventory.json"), raw, 0600)
}

func AuthorizeDomainOwner(ctx context.Context, h Host, id string) (func(), error) {
	st, err := LoadState(h)
	if err != nil || st == nil {
		return nil, ErrMaintenanceAuthorization
	}
	cfg, err := ReadBootConfig(h, ConfigPath)
	if err != nil || filepath.Clean(cfg.DataDir) != filepath.Clean(DataDir) {
		return nil, ErrMaintenanceAuthorization
	}
	return authorizeDomainData(ctx, cfg, id)
}

func authorizeDomainData(ctx context.Context, cfg *config.Config, id string) (func(), error) {
	lease, err := (&backup.Service{Cfg: cfg}).OpenData(false)
	if err != nil {
		return nil, ErrMaintenanceAuthorization
	}
	db, err := database.Open(cfg.DatabasePath, database.Options{ReadOnly: true, MaxConns: 1})
	if err != nil {
		lease.Close()
		return nil, ErrMaintenanceAuthorization
	}
	defer db.Close()
	var role auth.Role
	var enabled bool
	if db.QueryRowContext(ctx, `SELECT role,enabled FROM admins WHERE id=? AND reseller_id IS NULL`, id).Scan(&role, &enabled) != nil || role != auth.RoleOwner || !enabled {
		lease.Close()
		return nil, ErrMaintenanceAuthorization
	}
	return lease.Close, nil
}

// ReadDomainInput checks fixed private staging or controlled import sources.
// PEM payloads are cleared by the caller and never put in status/audit records.
func ReadDomainInput(h Host, st *State, r domainqueue.Request) (DomainOptions, error) {
	o := DomainOptions{Role: r.Role, Origin: r.Origin, Method: r.Method, Remove: r.Operation == "remove", ExpectedRevision: r.ExpectedRevision, Email: r.Email, Challenge: r.Challenge, Stdout: io.Discard}
	if r.Operation != "configure" || r.Method != domaintls.Manual {
		return o, nil
	}
	certPath, keyPath := r.CertSource, r.KeySource
	lineage := ""
	if r.StageID != "" {
		q := domainqueue.New(DataDir)
		var err error
		certPath, keyPath, err = q.ImportFiles(r.StageID)
		if err != nil {
			return o, err
		}
	} else if ControlledDomainSource(st, r.Role, certPath, keyPath) {
		if st != nil && filepath.Dir(certPath) == CertbotLivePath(st.Exposure.Lineage) {
			lineage = st.Exposure.Lineage
		}
	} else {
		policy, err := readDomainPolicy(h)
		site, ok := policy.Site(r.Role)
		candidate := domaintls.RenewalLineage(site)
		if err != nil || !ok || site.Method != domaintls.Automatic || certPath != CertbotLivePath(candidate)+"/fullchain.pem" || keyPath != CertbotLivePath(candidate)+"/privkey.pem" {
			return o, domainqueue.ErrInvalid
		}
		lineage = candidate
	}
	var err error
	o.CertPEM, o.KeyPEM, err = readDomainPairFiles(h, certPath, keyPath, lineage)
	return o, err
}

func inspectDomainBroker(h Host) ([]string, error) {
	files := []string{DomainBrokerServicePath, DomainBrokerPathPath, DomainBrokerTimerPath}
	contents := []string{RenderDomainBrokerService(), RenderDomainBrokerPath(), RenderDomainBrokerTimer()}
	present := false
	for i, file := range files {
		old, err := captureFile(h, file, 64<<10)
		if err != nil {
			return nil, err
		}
		if old.exists {
			if string(old.data) != contents[i] {
				return nil, fmt.Errorf("domains: refusing unowned host bridge")
			}
			present = true
		}
	}
	if !present {
		return nil, nil
	}
	owned := make([]string, 0, len(files)+4)
	for _, file := range files {
		if _, err := h.Stat(file); err == nil {
			owned = append(owned, file)
		}
	}
	for _, hook := range []struct{ path, content string }{{DomainRenewalPreHookPath, domainRenewalPreHook}, {CertbotDeployHookPath, certbotDeployHook}} {
		old, err := captureFile(h, hook.path, 64<<10)
		if err != nil {
			return nil, err
		}
		if old.exists {
			if string(old.data) != hook.content {
				return nil, fmt.Errorf("domains: refusing unowned renewal hook")
			}
			owned = append(owned, hook.path)
		}
	}
	owned = append(owned, domainqueue.New(DataDir).File("broker.json"))
	return owned, nil
}

func StopDomainBroker(ctx context.Context, h Host) ([]string, error) {
	files, err := inspectDomainBroker(h)
	if err != nil || len(files) == 0 {
		return files, err
	}
	if err := runQuiet(ctx, h, []string{"systemctl", "disable", "--now", "wg-guard-domains.path", "wg-guard-domains.timer"}, time.Minute); err != nil {
		return nil, err
	}
	if err := runQuiet(ctx, h, []string{"systemctl", "stop", "wg-guard-domains.service"}, time.Minute); err != nil {
		return nil, err
	}
	return files, nil
}

func domainArtifacts(h Host) ([]string, error) {
	p, err := readDomainPolicy(h)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	files := []string{layout.DomainPolicy}
	for _, site := range p.Sites {
		if site.CertificateID == "" {
			continue
		}
		cert, key, _ := domaintls.PairFiles(layout.DomainPolicy, site.CertificateID)
		files = addUnique(files, cert)
		files = addUnique(files, key)
	}
	return files, nil
}
