package install

import (
	"context"
	"crypto/x509"
	"errors"
	"fmt"
	"io/fs"
	"path/filepath"
	"time"

	"github.com/Sir-Adnan/wg-guard/internal/domaintls"
	"github.com/Sir-Adnan/wg-guard/internal/layout"
)

const DomainRenewalPreHookPath = "/etc/letsencrypt/renewal-hooks/pre/wg-guard-domains"
const domainRenewalPreHook = `#!/bin/sh
# Generated by wg-guard install
set -eu
exec /usr/local/bin/wg-guard domains challenge-prepare
`

func ensureDomainRenewalHooks(h Host) error {
	old, e := captureFile(h, DomainRenewalPreHookPath, 4096)
	if e != nil {
		return e
	}
	if old.exists && string(old.data) != domainRenewalPreHook {
		return fmt.Errorf("domains: renewal pre-hook is unowned")
	}
	if e := h.MkdirAll(filepath.Dir(DomainRenewalPreHookPath), 0755); e != nil {
		return e
	}
	if e := atomicWrite(h, DomainRenewalPreHookPath, []byte(domainRenewalPreHook), 0700); e != nil {
		return e
	}
	return ensureManagedDomainDeployHook(h)
}

func ensureManagedDomainDeployHook(h Host) error {
	old, e := captureFile(h, CertbotDeployHookPath, 64<<10)
	if e != nil {
		return e
	}
	if old.exists && string(old.data) != certbotDeployHook {
		return fmt.Errorf("domains: renewal deploy hook is unowned")
	}
	if e := h.MkdirAll(filepath.Dir(CertbotDeployHookPath), 0755); e != nil {
		return e
	}
	return atomicWrite(h, CertbotDeployHookPath, []byte(certbotDeployHook), 0700)
}

func PrepareDomainRenewalChallenges(ctx context.Context, h Host) error {
	if !h.IsRoot() {
		return terminalError("manage.root")
	}
	p, e := readDomainPolicy(h)
	if errors.Is(e, fs.ErrNotExist) {
		return nil
	}
	if e != nil {
		return e
	}
	hosts := make([]string, 0, 2)
	for _, site := range p.Sites {
		if site.Method == domaintls.Automatic {
			hosts = append(hosts, domainOriginHost(site.Origin))
		}
	}
	if len(hosts) == 0 {
		return nil
	}
	return writeJSON(h, filepath.Join(layout.DomainChallenges, "enrollment.json"), domaintls.Enrollment{Schema: domaintls.Schema, Hosts: hosts, ExpiresAt: time.Now().Add(15 * time.Minute)})
}

// The lifecycle lock stays available to Certbot's synchronous deploy hook.
func RenewDomainCertificate(ctx context.Context, h Host, role domaintls.Role) error {
	if !h.IsRoot() || !role.Valid() {
		return domaintls.ErrPolicy
	}
	if e := CheckLifecycleReady(h); e != nil {
		return e
	}
	p, e := readDomainPolicy(h)
	if e != nil {
		return e
	}
	site, ok := p.Site(role)
	if !ok || site.Method != domaintls.Automatic {
		return fmt.Errorf("domains: selected certificate is not host-managed automatic TLS")
	}
	if e := PrepareDomainRenewalChallenges(ctx, h); e != nil {
		return e
	}
	defer h.Remove(filepath.Join(layout.DomainChallenges, "enrollment.json"))
	if e := ensureDomainRenewalHooks(h); e != nil {
		return e
	}
	args := []string{CertbotPath, "renew", "--cert-name", domaintls.RenewalLineage(site), "--no-random-sleep-on-renew"}
	if site.Challenge == "http" {
		args = append(args, "--webroot", "--webroot-path", layout.DomainChallenges)
	}
	if e := runQuiet(ctx, h, args, longTimeout); e != nil {
		return fmt.Errorf("domains: certificate renewal check failed")
	}
	// Retry synchronization of valid renewed material after a prior hook failure,
	// without forcing another issuance or spending additional CA renewal quota.
	_, e = SyncDomainRenewal(ctx, h, CertbotLivePath(domaintls.RenewalLineage(site)))
	return e
}

func RenewDueDomains(ctx context.Context, h Host) error {
	_, e := readDomainPolicy(h)
	if errors.Is(e, fs.ErrNotExist) {
		return nil
	}
	if e != nil {
		return e
	}
	i, e := DomainStatus(ctx, h)
	if e != nil {
		return e
	}
	for _, certificate := range i.Certificates {
		if certificate.Site.Method == domaintls.Automatic && time.Until(certificate.Info.NotAfter) < 30*24*time.Hour {
			if e := RenewDomainCertificate(ctx, h, certificate.Site.Role); e != nil {
				return e
			}
		}
	}
	return nil
}

func SyncDomainRenewal(ctx context.Context, h Host, lineage string) (bool, error) {
	return syncDomainRenewal(ctx, h, lineage, nil)
}

func syncDomainRenewal(ctx context.Context, h Host, lineage string, roots *x509.CertPool) (bool, error) {
	p, e := readDomainPolicy(h)
	if errors.Is(e, fs.ErrNotExist) {
		return false, nil
	}
	if e != nil {
		return false, e
	}
	for _, site := range p.Sites {
		if site.Method != domaintls.Automatic || lineage != CertbotLivePath(domaintls.RenewalLineage(site)) {
			continue
		}
		cert, key, e := readDomainPairFiles(h, lineage+"/fullchain.pem", lineage+"/privkey.pem", domaintls.RenewalLineage(site))
		if e != nil {
			return true, e
		}
		defer clear(cert)
		defer clear(key)
		if _, _, e := domaintls.CheckPair(cert, key, []string{domainOriginHost(site.Origin)}, time.Now(), roots); e != nil {
			return true, e
		}
		active, _, _ := domaintls.PairFiles(layout.DomainPolicy, site.CertificateID)
		before, e := readBoundedFile(h, active, domaintls.MaxMaterialBytes)
		if e == nil {
			oldInfo, _ := inspectDomainLeaf(before)
			newInfo, _ := inspectDomainLeaf(cert)
			if oldInfo.Fingerprint != "" && oldInfo.Fingerprint == newInfo.Fingerprint {
				return true, nil
			}
		}
		_, e = ConfigureDomain(ctx, h, DomainOptions{Role: site.Role, Origin: site.Origin, Method: domaintls.Automatic, ExpectedRevision: p.Revision, CertPEM: cert, KeyPEM: key, Roots: roots})
		return true, e
	}
	return false, nil
}

// Retired WG-Guard-owned lineages must stop enrolling certificates through
// Certbot's global timer. Never revoke certificates or delete another lineage.
func retireDomainLineages(ctx context.Context, h Host, before, after domaintls.Policy) error {
	keep := map[string]bool{}
	for _, site := range after.Sites {
		if site.Method == domaintls.Automatic {
			keep[domaintls.RenewalLineage(site)] = true
		}
	}
	for _, site := range before.Sites {
		if site.Method != domaintls.Automatic {
			continue
		}
		lineage := domaintls.RenewalLineage(site)
		if keep[lineage] {
			continue
		}
		if err := runQuiet(ctx, h, []string{CertbotPath, "delete", "--non-interactive", "--cert-name", lineage}, time.Minute); err != nil {
			return fmt.Errorf("domains: active configuration is verified but retired certificate renewal cleanup failed")
		}
	}
	return nil
}

func removeUnreferencedDomainLineage(ctx context.Context, h Host, lineage string) error {
	p, err := readDomainPolicy(h)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	for _, site := range p.Sites {
		if site.Method == domaintls.Automatic && domaintls.RenewalLineage(site) == lineage {
			return nil
		}
	}
	file := "/etc/letsencrypt/renewal/" + lineage + ".conf"
	if _, real := h.(realHost); real {
		if err := safeHostPath(file); err != nil {
			return err
		}
	}
	if _, err := h.Stat(file); errors.Is(err, fs.ErrNotExist) {
		return nil
	} else if err != nil {
		return err
	}
	return runQuiet(ctx, h, []string{CertbotPath, "delete", "--non-interactive", "--cert-name", lineage}, time.Minute)
}
