package install

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/Sir-Adnan/wg-guard/internal/config"
)

// renderBootConfig serializes the plan's boot config as TOML bytes.
func renderBootConfig(p Plan) ([]byte, error) {
	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(p.BootConfig()); err != nil {
		return nil, err
	}
	// The encoder skips zero values; an explicit comment keeps the generated
	// file self-describing for operators.
	header := "# Generated by wg-guard install — paths, listener and TLS mode are\n" +
		"# restart-required; everything else lives in the panel Settings.\n"
	return append([]byte(header), buf.Bytes()...), nil
}

// prompt is the interactive wizard. In --yes mode it never reads stdin and
// never asks for confirmation.
type prompt struct {
	yes    bool
	reader *bufio.Reader
	out    io.Writer
}

func newPrompt(stdin io.Reader, out io.Writer, yes bool) *prompt {
	return &prompt{yes: yes, reader: bufio.NewReader(stdin), out: out}
}

// ask reads one line with a default; empty input returns the default.
func (q *prompt) ask(label, def string) (string, error) {
	if q.yes {
		return def, nil
	}
	if def != "" {
		fmt.Fprintf(q.out, "%s [%s]: ", label, def)
	} else {
		fmt.Fprintf(q.out, "%s: ", label)
	}
	line, err := q.reader.ReadString('\n')
	if err != nil && line == "" {
		return "", fmt.Errorf("read %s: %w", label, err)
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return def, nil
	}
	return line, nil
}

// askInt reads an integer with bounds; empty input returns the default.
func (q *prompt) askInt(label string, def, min, max int) (int, error) {
	for {
		raw, err := q.ask(label, strconv.Itoa(def))
		if err != nil {
			return 0, err
		}
		n, err := strconv.Atoi(raw)
		if err != nil || n < min || n > max {
			if q.yes {
				return 0, fmt.Errorf("%s %q invalid and --yes set", label, raw)
			}
			fmt.Fprintf(q.out, "  enter a number between %d and %d\n", min, max)
			continue
		}
		return n, nil
	}
}

// askChoice reads a numbered choice (1-based).
func (q *prompt) askChoice(label string, options []string, def int) (int, error) {
	if q.yes {
		return def, nil
	}
	fmt.Fprintf(q.out, "%s\n", label)
	for i, o := range options {
		marker := " "
		if i+1 == def {
			marker = ">"
		}
		fmt.Fprintf(q.out, "  %s %d) %s\n", marker, i+1, o)
	}
	for {
		raw, err := q.ask("Choice", strconv.Itoa(def))
		if err != nil {
			return 0, err
		}
		n, err := strconv.Atoi(raw)
		if err != nil || n < 1 || n > len(options) {
			fmt.Fprintf(q.out, "  enter 1-%d\n", len(options))
			continue
		}
		return n, nil
	}
}

// plan completes missing Plan fields interactively (no-op under --yes,
// which uses flags + defaults).
func (q *prompt) plan(p *Plan, h Host) error {
	if p.Mode == "" || !p.Mode.Valid() {
		n, err := q.askChoice("Installation mode:", []string{
			"Docker (recommended — declarative upgrades, isolated control plane)",
			"Native systemd service (no Docker required)",
		}, 1)
		if err != nil {
			return err
		}
		if n == 1 {
			p.Mode = ModeDocker
		} else {
			p.Mode = ModeNative
		}
	}

	domain, err := q.ask("Domain name (blank = IP-only access)", p.Domain)
	if err != nil {
		return err
	}
	p.Domain = domain

	if p.Domain == "" {
		n, err := q.askChoice("TLS mode (no domain):", []string{
			"Behind a reverse proxy — plain HTTP on loopback, proxy terminates TLS",
			"Development — plain HTTP on loopback only, NOT for production",
		}, 1)
		if err != nil {
			return err
		}
		if n == 1 {
			p.TLSMode = config.TLSModeProxy
		} else {
			p.TLSMode = config.TLSModeDev
		}
	} else {
		n, err := q.askChoice(fmt.Sprintf("TLS mode for %s:", p.Domain), []string{
			"Automatic certificate (ACME/Let's Encrypt) — recommended; needs port 80 reachable",
			"Manual certificates — provide cert/key file paths",
		}, 1)
		if err != nil {
			return err
		}
		if n == 1 {
			p.TLSMode = config.TLSModeACME
		} else {
			p.TLSMode = config.TLSModeManual
		}
	}

	switch p.TLSMode {
	case config.TLSModeACME:
		defPort := p.PanelPort
		if defPort == 8080 {
			defPort = 443
		}
		if p.PanelPort, err = q.askInt("Panel HTTPS port", defPort, 1, 65535); err != nil {
			return err
		}
		if p.ACMEHTTPPort, err = q.askInt("ACME challenge (HTTP) port", 80, 1, 65535); err != nil {
			return err
		}
	case config.TLSModeManual:
		if p.PanelPort, err = q.askInt("Panel HTTPS port", 443, 1, 65535); err != nil {
			return err
		}
		if p.CertFile, err = q.ask("TLS certificate file", p.CertFile); err != nil {
			return err
		}
		if p.KeyFile, err = q.ask("TLS key file", p.KeyFile); err != nil {
			return err
		}
	default: // proxy / dev
		if p.PanelPort, err = q.askInt("Panel HTTP port", p.PanelPort, 1, 65535); err != nil {
			return err
		}
	}

	if p.Mode == ModeDocker {
		if img, err := q.ask("Container image", p.Image); err != nil {
			return err
		} else {
			p.Image = img
		}
	}
	return nil
}

// confirm prints the resolved plan and asks for confirmation (skipped under
// --yes).
func (q *prompt) confirm(p Plan) error {
	if q.yes {
		return nil
	}
	fmt.Fprintln(q.out, "\nInstallation plan")
	fmt.Fprintf(q.out, "  mode       %s\n", p.Mode)
	fmt.Fprintf(q.out, "  panel      %s\n", p.PanelURL())
	fmt.Fprintf(q.out, "  tls        %s", p.TLSMode)
	switch p.TLSMode {
	case config.TLSModeACME:
		fmt.Fprintf(q.out, " (domain %s, challenge port %d)", p.Domain, p.ACMEHTTPPort)
	case config.TLSModeManual:
		fmt.Fprintf(q.out, " (cert %s, key %s)", p.CertFile, p.KeyFile)
	}
	fmt.Fprintln(q.out)
	if p.Mode == ModeDocker {
		fmt.Fprintf(q.out, "  image      %s\n", p.Image)
	}
	fmt.Fprintf(q.out, "  config     %s\n", p.BootConfigPath())
	fmt.Fprintf(q.out, "  data       %s\n", p.DataDir)
	fmt.Fprintln(q.out)
	raw, err := q.ask("Proceed with installation? (yes/no)", "yes")
	if err != nil {
		return err
	}
	switch strings.ToLower(raw) {
	case "y", "yes":
		return nil
	}
	return fmt.Errorf("install: cancelled")
}
