package install

import (
	"bytes"
	"fmt"
	"io"
	"net"
	"regexp"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/Sir-Adnan/wg-guard/internal/config"
	"github.com/Sir-Adnan/wg-guard/internal/i18n"
	"github.com/Sir-Adnan/wg-guard/internal/settings"
	"github.com/Sir-Adnan/wg-guard/internal/terminal"
)

func renderBootConfig(p Plan) ([]byte, error) {
	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(p.BootConfig()); err != nil {
		return nil, err
	}
	return append([]byte("# Generated by wg-guard install; listener/TLS/path changes require restart.\n"), buf.Bytes()...), nil
}

type prompt struct {
	yes bool
	ui  *terminal.UI
	out io.Writer
}

func newPrompt(in io.Reader, out io.Writer, yes bool) *prompt {
	return &prompt{yes: yes, ui: terminal.New(in, out, terminal.Detect(in, out, i18n.En)), out: out}
}
func (q *prompt) t(key string, args ...any) string { return q.ui.T("setup."+key, args...) }
func (q *prompt) ask(label, def string) (string, error) {
	if q.yes {
		return def, nil
	}
	return q.ui.Ask(label, def)
}
func (q *prompt) askInt(label string, def, min, max int) (int, error) {
	for {
		v, err := q.ask(label, strconv.Itoa(def))
		if err != nil {
			return 0, err
		}
		n, e := strconv.Atoi(terminal.Digits(v))
		if e == nil && n >= min && n <= max {
			return n, nil
		}
		if q.yes {
			return 0, fmt.Errorf("%s", q.t("range", min, max))
		}
		q.ui.Text(q.t("range", min, max))
	}
}
func (q *prompt) askChoice(label string, options []string, def int) (int, error) {
	if q.yes {
		return def, nil
	}
	return q.ui.Choose(label, options, def)
}
func (q *prompt) askSecret(label string) (string, error) {
	if q.yes {
		return "", nil
	}
	return q.ui.Secret(label)
}
func (q *prompt) askYesNo(label string, def bool) (bool, error) {
	if q.yes {
		return def, nil
	}
	if !def {
		return q.ui.Confirm(label)
	}
	for {
		v, err := q.ask(label+" "+q.ui.T("terminal.yes_no"), "yes")
		if err != nil {
			return false, err
		}
		switch strings.ToLower(v) {
		case "y", "yes":
			return true, nil
		case "n", "no":
			return false, nil
		}
		q.ui.Text(q.ui.T("terminal.yes_no"))
	}
}

// plan uses one streaming input object for every field, including hidden secrets.
// Back returns control to the caller; no partial plan is ever applied.
func (q *prompt) plan(p *Plan, h Host) error {
	if q.yes {
		return nil
	}
	q.ui.Section("WG-Guard")
	q.ui.Text(q.t("intro"))
	var err error
	if !p.Mode.Valid() {
		n, e := q.askChoice(q.t("mode"), []string{q.t("docker"), q.t("native")}, 1)
		if e != nil {
			return e
		}
		p.Mode = ModeDocker
		if n == 2 {
			p.Mode = ModeNative
		}
	}
	q.ui.Section(q.t("address"))
	p.Domain, err = q.ask(q.t("domain"), p.Domain)
	if err != nil {
		return err
	}
	if p.Domain == "" {
		p.PublicIP, err = q.ask(q.t("ip"), p.PublicIP)
		if err != nil {
			return err
		}
	}
	if p.TLSMode == config.TLSModeDev && !p.TLSModeExplicit {
		if p.Domain == "" {
			n, e := q.askChoice(q.t("tls"), []string{q.t("proxy"), q.t("dev")}, 1)
			if e != nil {
				return e
			}
			p.TLSMode = config.TLSModeProxy
			if n == 2 {
				p.TLSMode = config.TLSModeDev
			}
		} else {
			n, e := q.askChoice(q.t("tls"), []string{q.t("acme"), q.t("manual")}, 1)
			if e != nil {
				return e
			}
			p.TLSMode = config.TLSModeACME
			if n == 2 {
				p.TLSMode = config.TLSModeManual
			}
		}
	}
	def := p.PanelPort
	if (p.TLSMode == config.TLSModeACME || p.TLSMode == config.TLSModeManual) && !p.PanelPortExplicit {
		def = 443
	}
	p.PanelPort, err = q.askInt(q.t("panel_port"), def, 1, 65535)
	if err != nil {
		return err
	}
	p.PanelPortExplicit = true
	if p.TLSMode == config.TLSModeACME {
		q.ui.Text(q.t("http01"))
		p.ACMEHTTPPort, err = q.askInt(q.t("acme_port"), p.ACMEHTTPPort, 1, 65535)
		if err != nil {
			return err
		}
	}
	if p.TLSMode == config.TLSModeManual {
		p.CertFile, err = q.ask(q.t("cert"), p.CertFile)
		if err != nil {
			return err
		}
		p.KeyFile, err = q.ask(q.t("key"), p.KeyFile)
		if err != nil {
			return err
		}
	}
	if err := q.planNetwork(p); err != nil {
		return err
	}
	if err := q.planTelegram(p); err != nil {
		return err
	}
	if p.Mode == ModeDocker {
		p.Image, err = q.ask(q.t("image"), p.Image)
	}
	return err
}
func (q *prompt) planNetwork(p *Plan) error {
	q.ui.Section(q.t("network"))
	q.ui.Text(q.t("network_defaults"))
	yes, err := q.askYesNo(q.t("custom_network"), false)
	if err != nil || !yes {
		return err
	}
	p.PortMin, err = q.askInt(q.t("port_min"), 30000, 1024, 65535)
	if err != nil {
		return err
	}
	for {
		p.PortMax, err = q.askInt(q.t("port_max"), 50000, 1024, 65535)
		if err != nil {
			return err
		}
		if p.PortMax >= p.PortMin {
			break
		}
		q.ui.Text(q.t("port_order"))
	}
	for {
		p.VPNSubnet, err = q.ask(q.t("pool"), builtInPool)
		if err != nil {
			return err
		}
		if settings.ValidSubnet(p.VPNSubnet) == nil {
			break
		}
		q.ui.Text(q.t("cidr_invalid"))
	}
	if p.VPNSubnet == builtInPool {
		p.VPNSubnet = ""
	}
	p.MTU, err = q.askInt(q.t("mtu"), 1420, 576, 65535)
	if err != nil {
		return err
	}
	for {
		p.ClientDNS, err = q.ask(q.t("dns"), "1.1.1.1, 1.0.0.1")
		if err != nil {
			return err
		}
		if validIPList(p.ClientDNS) {
			break
		}
		q.ui.Text(q.t("dns_invalid"))
	}
	return nil
}
func (q *prompt) planTelegram(p *Plan) error {
	q.ui.Section(q.t("backup"))
	yes, err := q.askYesNo(q.t("telegram"), false)
	if err != nil || !yes {
		return err
	}
	token, err := q.askSecret(q.t("token"))
	if err != nil {
		return err
	}
	if token == "" {
		q.ui.Text(q.t("token_skipped"))
		return nil
	}
	for {
		p.TelegramChat, err = q.ask(q.t("chat"), "")
		if err != nil {
			return err
		}
		p.TelegramChat = terminal.Digits(p.TelegramChat)
		if validChatID(p.TelegramChat) {
			break
		}
		q.ui.Text(q.t("chat_invalid"))
	}
	for {
		p.TelegramTime, err = q.ask(q.t("time"), "03:30")
		if err != nil {
			return err
		}
		p.TelegramTime = terminal.Digits(p.TelegramTime)
		if dailyTimeRe.MatchString(p.TelegramTime) {
			break
		}
		q.ui.Text(q.t("time_invalid"))
	}
	p.TelegramToken = token
	return nil
}
func (q *prompt) confirm(p Plan) error {
	if q.yes {
		return nil
	}
	q.ui.Section(q.t("review"))
	for _, field := range []struct{ k, v string }{
		{"mode", string(p.Mode)}, {"panel", p.PanelURL()}, {"endpoint", p.VPNEndpoint()}, {"tls", string(p.TLSMode)}, {"config", p.BootConfigPath()}, {"data", p.DataDir},
	} {
		q.ui.Field(q.t(field.k), field.v)
	}
	if p.Mode == ModeDocker {
		q.ui.Field(q.t("image"), p.Image)
	}
	lo, hi := p.PortMin, p.PortMax
	if lo == 0 {
		lo = 30000
	}
	if hi == 0 {
		hi = 50000
	}
	q.ui.Field(q.t("udp"), fmt.Sprintf("%d–%d", lo, hi))
	pool, mtu, dns := p.VPNSubnet, p.MTU, p.ClientDNS
	if pool == "" {
		pool = "10.8.0.0/24"
	}
	if mtu == 0 {
		mtu = 1420
	}
	if dns == "" {
		dns = "1.1.1.1, 1.0.0.1"
	}
	q.ui.Field(q.t("pool"), pool)
	q.ui.Field(q.t("mtu"), strconv.Itoa(mtu))
	q.ui.Field(q.t("dns"), dns)
	if p.TLSMode == config.TLSModeACME {
		q.ui.Text(q.t("http01"))
	}
	if p.TelegramToken != "" {
		q.ui.Field(q.t("backup"), q.t("backup_set", p.TelegramChat, p.TelegramTime))
	} else {
		q.ui.Text(q.t("backup_later"))
	}
	q.ui.Text(q.t("impact"))
	q.ui.Text(q.t("owner"))
	ok, err := q.ui.Confirm(q.t("proceed"))
	if err != nil {
		return err
	}
	if !ok {
		return terminal.ErrCanceled
	}
	return nil
}
func validChatID(s string) bool {
	if s == "" || strings.HasPrefix(s, "+") {
		return false
	}
	n, err := strconv.ParseInt(s, 10, 64)
	return err == nil && n != 0
}

var dailyTimeRe = regexp.MustCompile(`^([01]\d|2[0-3]):[0-5]\d$`)

func validIPList(s string) bool {
	for _, part := range strings.Split(s, ",") {
		part = strings.TrimSpace(part)
		if part == "" || net.ParseIP(part) == nil {
			return false
		}
	}
	return true
}
func isDigits(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}
