package install

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"net"
	"os"
	"regexp"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/Sir-Adnan/wg-guard/internal/config"
	"github.com/Sir-Adnan/wg-guard/internal/settings"
	"golang.org/x/term"
)

// renderBootConfig serializes the plan's boot config as TOML bytes.
func renderBootConfig(p Plan) ([]byte, error) {
	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(p.BootConfig()); err != nil {
		return nil, err
	}
	// The encoder skips zero values; an explicit comment keeps the generated
	// file self-describing for operators.
	header := "# Generated by wg-guard install — paths, listener and TLS mode are\n" +
		"# restart-required; everything else lives in the panel Settings.\n"
	return append([]byte(header), buf.Bytes()...), nil
}

// prompt is the interactive wizard. In --yes mode it never reads stdin and
// never asks for confirmation.
type prompt struct {
	yes    bool
	reader *bufio.Reader
	out    io.Writer
}

func newPrompt(stdin io.Reader, out io.Writer, yes bool) *prompt {
	return &prompt{yes: yes, reader: bufio.NewReader(stdin), out: out}
}

// ask reads one line with a default; empty input returns the default.
func (q *prompt) ask(label, def string) (string, error) {
	if q.yes {
		return def, nil
	}
	if def != "" {
		fmt.Fprintf(q.out, "%s [%s]: ", label, def)
	} else {
		fmt.Fprintf(q.out, "%s: ", label)
	}
	line, err := q.reader.ReadString('\n')
	if err != nil && line == "" {
		return "", fmt.Errorf("read %s: %w", label, err)
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return def, nil
	}
	return line, nil
}

// askInt reads an integer with bounds; empty input returns the default.
func (q *prompt) askInt(label string, def, min, max int) (int, error) {
	for {
		raw, err := q.ask(label, strconv.Itoa(def))
		if err != nil {
			return 0, err
		}
		n, err := strconv.Atoi(raw)
		if err != nil || n < min || n > max {
			if q.yes {
				return 0, fmt.Errorf("%s %q invalid and --yes set", label, raw)
			}
			fmt.Fprintf(q.out, "  enter a number between %d and %d\n", min, max)
			continue
		}
		return n, nil
	}
}

// askChoice reads a numbered choice (1-based).
func (q *prompt) askChoice(label string, options []string, def int) (int, error) {
	if q.yes {
		return def, nil
	}
	fmt.Fprintf(q.out, "%s\n", label)
	for i, o := range options {
		marker := " "
		if i+1 == def {
			marker = ">"
		}
		fmt.Fprintf(q.out, "  %s %d) %s\n", marker, i+1, o)
	}
	for {
		raw, err := q.ask("Choice", strconv.Itoa(def))
		if err != nil {
			return 0, err
		}
		n, err := strconv.Atoi(raw)
		if err != nil || n < 1 || n > len(options) {
			fmt.Fprintf(q.out, "  enter 1-%d\n", len(options))
			continue
		}
		return n, nil
	}
}

// plan completes missing Plan fields interactively (no-op under --yes,
// which uses flags + defaults only — explicit flags must never be silently
// overridden by prompt defaults).
func (q *prompt) plan(p *Plan, h Host) error {
	if q.yes {
		return nil
	}
	if p.Mode == "" || !p.Mode.Valid() {
		n, err := q.askChoice("Installation mode:", []string{
			"Docker (recommended — declarative upgrades, isolated control plane)",
			"Native systemd service (no Docker required)",
		}, 1)
		if err != nil {
			return err
		}
		if n == 1 {
			p.Mode = ModeDocker
		} else {
			p.Mode = ModeNative
		}
	}

	domain, err := q.ask("Domain name (blank = IP-only access)", p.Domain)
	if err != nil {
		return err
	}
	p.Domain = domain

	// TLS mode: an explicit --tls value is kept; the dev sentinel means
	// "not chosen yet" and is prompted (Resolve derives ACME from a domain).
	if p.TLSMode == config.TLSModeDev {
		if p.Domain == "" {
			n, err := q.askChoice("TLS mode (no domain):", []string{
				"Behind a reverse proxy — plain HTTP on loopback, proxy terminates TLS",
				"Development — plain HTTP on loopback only, NOT for production",
			}, 1)
			if err != nil {
				return err
			}
			if n == 1 {
				p.TLSMode = config.TLSModeProxy
			} else {
				p.TLSMode = config.TLSModeDev
			}
		} else {
			n, err := q.askChoice(fmt.Sprintf("TLS mode for %s:", p.Domain), []string{
				"Automatic certificate (ACME/Let's Encrypt) — recommended; needs port 80 reachable",
				"Manual certificates — provide cert/key file paths",
			}, 1)
			if err != nil {
				return err
			}
			if n == 1 {
				p.TLSMode = config.TLSModeACME
			} else {
				p.TLSMode = config.TLSModeManual
			}
		}
	}

	switch p.TLSMode {
	case config.TLSModeACME:
		defPort := p.PanelPort
		if defPort == 8080 {
			defPort = 443
		}
		if p.PanelPort, err = q.askInt("Panel HTTPS port", defPort, 1, 65535); err != nil {
			return err
		}
		if p.ACMEHTTPPort, err = q.askInt("ACME challenge (HTTP) port", 80, 1, 65535); err != nil {
			return err
		}
	case config.TLSModeManual:
		if p.PanelPort, err = q.askInt("Panel HTTPS port", 443, 1, 65535); err != nil {
			return err
		}
		if p.CertFile, err = q.ask("TLS certificate file", p.CertFile); err != nil {
			return err
		}
		if p.KeyFile, err = q.ask("TLS key file", p.KeyFile); err != nil {
			return err
		}
	default: // proxy / dev
		if p.PanelPort, err = q.askInt("Panel HTTP port", p.PanelPort, 1, 65535); err != nil {
			return err
		}
	}

	if err := q.planNetwork(p); err != nil {
		return err
	}
	if err := q.planTelegram(p); err != nil {
		return err
	}

	if p.Mode == ModeDocker {
		if img, err := q.ask("Container image", p.Image); err != nil {
			return err
		} else {
			p.Image = img
		}
	}
	return nil
}

// planNetwork offers the VPN networking defaults behind a y/N gate: Enter
// everywhere keeps the recommended defaults, so a normal install stays
// short. Customized values are seeded into the settings registry before the
// service first boots.
func (q *prompt) planNetwork(p *Plan) error {
	yes, err := q.askYesNo("Customize VPN network defaults? (AWG port range, VPN subnet, MTU, client DNS — Enter keeps all defaults)", false)
	if err != nil || !yes {
		return err
	}
	if p.PortMin, err = q.askInt("AWG listen-port allocation range — start", 30000, 1024, 65535); err != nil {
		return err
	}
	for {
		if p.PortMax, err = q.askInt("AWG listen-port allocation range — end", 50000, 1024, 65535); err != nil {
			return err
		}
		if p.PortMax >= p.PortMin {
			break
		}
		fmt.Fprintf(q.out, "  end must be ≥ start (%d)\n", p.PortMin)
	}
	for {
		if p.VPNSubnet, err = q.ask("VPN subnet pool for the first interface (awg0)", builtInPool); err != nil {
			return err
		}
		if err := settings.ValidSubnet(p.VPNSubnet); err == nil {
			break
		}
		fmt.Fprintln(q.out, "  enter a valid IPv4 CIDR, e.g. 10.8.0.0/24")
	}
	if p.VPNSubnet == builtInPool {
		p.VPNSubnet = "" // the built-in ladder default needs no explicit setting
	}
	if p.MTU, err = q.askInt("Client MTU", 1420, 576, 65535); err != nil {
		return err
	}
	for {
		if p.ClientDNS, err = q.ask("Client DNS servers (comma-separated IPs)", "1.1.1.1, 1.0.0.1"); err != nil {
			return err
		}
		if validIPList(p.ClientDNS) {
			break
		}
		fmt.Fprintln(q.out, "  every entry must be an IP address")
	}
	return nil
}

// planTelegram offers Telegram backup delivery behind a y/N gate; skipping
// keeps the panel defaults (the backup settings live in the panel under
// Settings → Backups).
func (q *prompt) planTelegram(p *Plan) error {
	yes, err := q.askYesNo("Set up Telegram backups now? (bot token, chat ID, daily schedule — can be configured later in the panel)", false)
	if err != nil || !yes {
		return err
	}
	token, err := q.askSecret("Telegram bot token (from @BotFather; hidden on terminals)")
	if err != nil {
		return err
	}
	if token == "" {
		fmt.Fprintln(q.out, "  no token entered — skipping (configure later in the panel)")
		return nil
	}
	for {
		if p.TelegramChat, err = q.ask("Telegram chat ID (numeric — message the bot once, then check it)", ""); err != nil {
			return err
		}
		if isDigits(p.TelegramChat) {
			break
		}
		fmt.Fprintln(q.out, "  chat ID must be numeric")
	}
	for {
		if p.TelegramTime, err = q.ask("Daily backup time (UTC, HH:MM)", "03:30"); err != nil {
			return err
		}
		if dailyTimeRe.MatchString(p.TelegramTime) {
			break
		}
		fmt.Fprintln(q.out, "  enter the time as HH:MM (00:00–23:59)")
	}
	p.TelegramToken = token
	return nil
}

// dailyTimeRe matches the HH:MM the backup scheduler accepts (UTC).
var dailyTimeRe = regexp.MustCompile(`^([01]\d|2[0-3]):[0-5]\d$`)

func validIPList(s string) bool {
	for _, part := range strings.Split(s, ",") {
		part = strings.TrimSpace(part)
		if part == "" || net.ParseIP(part) == nil {
			return false
		}
	}
	return true
}

func isDigits(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

// askYesNo reads a yes/no answer; empty input returns def (Enter = default).
func (q *prompt) askYesNo(label string, def bool) (bool, error) {
	choice := "n"
	if def {
		choice = "y"
	}
	raw, err := q.ask(label, choice)
	if err != nil {
		return false, err
	}
	switch strings.ToLower(raw) {
	case "y", "yes":
		return true, nil
	case "n", "no":
		return false, nil
	}
	return def, nil
}

// askSecret reads a secret: without echo when stdin is a terminal (x/term),
// plain line read when piped (scripted installs, tests). The value travels
// to the CLI via stdin — never argv, never output.
func (q *prompt) askSecret(label string) (string, error) {
	if q.yes {
		return "", nil
	}
	fmt.Fprintf(q.out, "%s: ", label)
	fd := int(os.Stdin.Fd())
	if term.IsTerminal(fd) {
		b, err := term.ReadPassword(fd)
		fmt.Fprintln(q.out)
		if err != nil {
			return "", fmt.Errorf("read %s: %w", label, err)
		}
		return strings.TrimSpace(string(b)), nil
	}
	line, err := q.reader.ReadString('\n')
	if err != nil && line == "" {
		return "", fmt.Errorf("read %s: %w", label, err)
	}
	return strings.TrimSpace(line), nil
}

// confirm prints the resolved plan and asks for confirmation (skipped under
// --yes).
func (q *prompt) confirm(p Plan) error {
	if q.yes {
		return nil
	}
	fmt.Fprintln(q.out, "\nInstallation plan")
	fmt.Fprintf(q.out, "  mode       %s\n", p.Mode)
	fmt.Fprintf(q.out, "  panel      %s\n", p.PanelURL())
	fmt.Fprintf(q.out, "  tls        %s", p.TLSMode)
	switch p.TLSMode {
	case config.TLSModeACME:
		fmt.Fprintf(q.out, " (domain %s, challenge port %d)", p.Domain, p.ACMEHTTPPort)
	case config.TLSModeManual:
		fmt.Fprintf(q.out, " (cert %s, key %s)", p.CertFile, p.KeyFile)
	}
	fmt.Fprintln(q.out)
	if p.Mode == ModeDocker {
		fmt.Fprintf(q.out, "  image      %s\n", p.Image)
	}
	if p.PortMin != 0 || p.PortMax != 0 {
		fmt.Fprintf(q.out, "  awg ports  %d–%d\n", p.PortMin, p.PortMax)
	}
	if p.VPNSubnet != "" {
		fmt.Fprintf(q.out, "  vpn pool   %s (first interface)\n", p.VPNSubnet)
	}
	if p.MTU != 0 {
		fmt.Fprintf(q.out, "  mtu        %d\n", p.MTU)
	}
	if p.ClientDNS != "" {
		fmt.Fprintf(q.out, "  client dns %s\n", p.ClientDNS)
	}
	if p.TelegramToken != "" {
		fmt.Fprintf(q.out, "  telegram   chat %s, daily %s UTC\n", p.TelegramChat, p.TelegramTime)
	} else {
		fmt.Fprintf(q.out, "  telegram   not configured (panel → Backups)\n")
	}
	fmt.Fprintf(q.out, "  config     %s\n", p.BootConfigPath())
	fmt.Fprintf(q.out, "  data       %s\n", p.DataDir)
	fmt.Fprintln(q.out)
	raw, err := q.ask("Proceed with installation? (yes/no)", "yes")
	if err != nil {
		return err
	}
	switch strings.ToLower(raw) {
	case "y", "yes":
		return nil
	}
	return fmt.Errorf("install: cancelled")
}
