package install

import (
	"fmt"
	"strings"
)

const (
	OperationRetentionDir  = "/etc/tmpfiles.d"
	OperationRetentionPath = OperationRetentionDir + "/wg-guard-operations.conf"
)

const dockerLogPolicy = `    logging:
      driver: local
      options:
        max-size: "16m"
        max-file: "8"
        compress: "true"
`

// RenderCompose generates the compose file for a docker-mode install: host
// networking + CAP_NET_ADMIN put links, nftables and tc on the host netns
// (ADR-0006); the boot config is read-only, the data dir read-write. The
// healthcheck matches the deployed TLS mode (see HealthProbeURL).
func RenderCompose(p Plan) string {
	probe, skipVerify, _ := p.HealthProbeURL()
	var b strings.Builder
	b.WriteString("# Generated by wg-guard install — edit ports in the boot config, then restart.\n")
	b.WriteString("name: wg-guard\n\nservices:\n  wg-guard:\n")
	fmt.Fprintf(&b, "    image: %s\n", p.Image)
	b.WriteString("    container_name: wg-guard\n")
	b.WriteString("    network_mode: host\n")
	b.WriteString("    pull_policy: never\n")
	b.WriteString("    cap_drop: [ALL]\n    cap_add:\n      - NET_ADMIN\n      - NET_BIND_SERVICE\n")
	b.WriteString("    security_opt:\n      - no-new-privileges:true\n    read_only: true\n")
	b.WriteString("    tmpfs:\n      - /run:rw,nosuid,nodev,size=32m\n      - /tmp:rw,nosuid,nodev,size=64m\n")
	b.WriteString("    devices:\n      - /dev/net/tun:/dev/net/tun\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString(dockerLogPolicy)
	b.WriteString("    volumes:\n")
	fmt.Fprintf(&b, "      - %s:/etc/wg-guard/wg-guard.toml:ro\n", p.BootConfigPath())
	fmt.Fprintf(&b, "      - %s:/var/lib/wg-guard\n", p.DataDir)
	if p.TLSMode == "manual" {
		for _, file := range []string{p.CertFile, p.KeyFile} {
			fmt.Fprintf(&b, "      - %s:%s:ro\n", file, file)
		}
	}
	fmt.Fprintf(&b, "    healthcheck:\n")
	extra := ""
	if skipVerify {
		extra = "\"-k\", "
	}
	fmt.Fprintf(&b, "      test: [\"CMD\", \"curl\", \"-fsS\", \"-o\", \"/dev/null\", %s\"%s\"]\n", extra, probe)
	b.WriteString("      interval: 30s\n      timeout: 5s\n      retries: 3\n      start_period: 15s\n")
	return b.String()
}

// RenderOperationRetention lets Ubuntu's existing tmpfiles-clean timer remove
// inactive daily operation files by mtime even when no new lifecycle runs.
func RenderOperationRetention() string {
	return "d /var/lib/wg-guard/operations 0700 root root m:7d -\n"
}

// BootConfigPath is the in-container config mount source for this plan.
func (p Plan) BootConfigPath() string {
	if p.EtcDir != "" && p.EtcDir != EtcDir {
		return p.EtcDir + "/wg-guard.toml"
	}
	return ConfigPath
}

// hostCommands are dispatched by the mode-aware binary itself when it runs on
// a docker-mode host: they act on the compose project, the systemd unit or
// the host's own state — inside the container they are meaningless.
var hostCommands = map[string]bool{
	"manage": true, "owner-bootstrap": true, "restart": true, "restore": true,
	"core":                  true,
	"tls-check":             true,
	"certificate-sync":      true,
	"exposure":              true,
	"install":               true,
	"recover-install":       true,
	"update":                true,
	"update-broker-install": true,
	"update-request-run":    true,
	"uninstall":             true,
	"status":                true,
	"logs":                  true,
	"doctor":                true,
	"version":               true,
	"image-import":          true,
	"help":                  true,
	"-h":                    true,
	"--help":                true,
}

// Route returns how the binary should run one command in docker mode:
// "container" (exec into the shared-volume container), "host" (run locally),
// or "refuse" (serve is owned by compose; install by the host installer).
func Route(cmd string) string {
	switch cmd {
	case "serve":
		return "refuse"
	}
	if hostCommands[cmd] {
		return "host"
	}
	return "container"
}

// RenderShim is the docker-mode host entry point. It is the full wg-guard
// binary; this content documents the dispatch contract the binary implements
// via Route (kept as a comment for auditors, not executed).
//
// Routing rules (see Route):
//   - serve            → refused: `docker compose -f /etc/wg-guard/compose.yaml up -d` owns it
//   - install/update/uninstall/status/doctor/version → host
//   - everything else  → docker exec -i wg-guard /usr/local/bin/wg-guard …
const ShimDoc = `mode-aware dispatch: host commands run locally, panel/data commands exec
into the wg-guard container (canonical shared data layout).`
