package install

import (
	"fmt"
	"strings"
)

// RenderCompose generates the compose file for a docker-mode install: host
// networking + CAP_NET_ADMIN put links, nftables and tc on the host netns
// (ADR-0006); the boot config is read-only, the data dir read-write. The
// healthcheck matches the deployed TLS mode (see HealthProbeURL).
func RenderCompose(p Plan) string {
	probe, skipVerify, _ := p.HealthProbeURL()
	var b strings.Builder
	b.WriteString("# Generated by wg-guard install — edit ports in the boot config, then restart.\n")
	b.WriteString("name: wg-guard\n\nservices:\n  wg-guard:\n")
	fmt.Fprintf(&b, "    image: %s\n", p.Image)
	b.WriteString("    container_name: wg-guard\n")
	b.WriteString("    network_mode: host\n")
	b.WriteString("    cap_add:\n      - NET_ADMIN\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    volumes:\n")
	fmt.Fprintf(&b, "      - %s:/etc/wg-guard/wg-guard.toml:ro\n", p.BootConfigPath())
	fmt.Fprintf(&b, "      - %s:/var/lib/wg-guard\n", p.DataDir)
	if p.TLSMode == "manual" {
		for _, file := range []string{p.CertFile, p.KeyFile} {
			fmt.Fprintf(&b, "      - %s:%s:ro\n", file, file)
		}
	}
	fmt.Fprintf(&b, "    healthcheck:\n")
	extra := ""
	if skipVerify {
		extra = "\"-k\", "
	}
	fmt.Fprintf(&b, "      test: [\"CMD\", \"curl\", \"-fsS\", \"-o\", \"/dev/null\", %s\"%s\"]\n", extra, probe)
	b.WriteString("      interval: 30s\n      timeout: 5s\n      retries: 3\n      start_period: 15s\n")
	return b.String()
}

// BootConfigPath is the in-container config mount source for this plan.
func (p Plan) BootConfigPath() string {
	if p.EtcDir != "" && p.EtcDir != EtcDir {
		return p.EtcDir + "/wg-guard.toml"
	}
	return ConfigPath
}

// hostCommands are dispatched by the mode-aware binary itself when it runs on
// a docker-mode host: they act on the compose project, the systemd unit or
// the host's own state — inside the container they are meaningless.
var hostCommands = map[string]bool{
	"core":      true,
	"tls-check": true,
	"install":   true,
	"update":    true,
	"uninstall": true,
	"status":    true,
	"doctor":    true,
	"version":   true,
	"help":      true,
	"-h":        true,
	"--help":    true,
}

// Route returns how the binary should run one command in docker mode:
// "container" (exec into the shared-volume container), "host" (run locally),
// or "refuse" (serve is owned by compose; install by the host installer).
func Route(cmd string) string {
	switch cmd {
	case "serve":
		return "refuse"
	}
	if hostCommands[cmd] {
		return "host"
	}
	return "container"
}

// RenderShim is the docker-mode host entry point. It is the full wg-guard
// binary; this content documents the dispatch contract the binary implements
// via Route (kept as a comment for auditors, not executed).
//
// Routing rules (see Route):
//   - serve            → refused: `docker compose -f /etc/wg-guard/compose.yaml up -d` owns it
//   - install/update/uninstall/status/doctor/version → host
//   - everything else  → docker exec -i wg-guard /usr/local/bin/wg-guard …
const ShimDoc = `mode-aware dispatch: host commands run locally, panel/data commands exec
into the wg-guard container (same volume layout as native mode).`

// RenderUnit generates the hardened systemd unit for native mode. The panel
// needs NET_ADMIN (links, nftables, tc) and NET_BIND_SERVICE (ports <1024);
// ProtectKernelTunables makes /proc/sys read-only, so the one sysctl the
// panel writes (net.ipv4.ip_forward) is re-admitted through ReadWritePaths.
func RenderUnit(p Plan) string {
	var b strings.Builder
	b.WriteString("# Generated by wg-guard install\n")
	b.WriteString("[Unit]\n")
	b.WriteString("Description=WG-Guard VPN node panel\n")
	b.WriteString("Documentation=https://github.com/Sir-Adnan/wg-guard\n")
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n\n")
	b.WriteString("[Service]\n")
	b.WriteString("Type=simple\n")
	fmt.Fprintf(&b, "ExecStart=%s serve -config %s\n", BinPath, p.BootConfigPath())
	b.WriteString("Restart=on-failure\n")
	b.WriteString("RestartSec=5s\n")
	b.WriteString("LimitNOFILE=65535\n\n")
	b.WriteString("AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE\n")
	b.WriteString("CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE\n")
	b.WriteString("NoNewPrivileges=true\n")
	b.WriteString("ProtectSystem=strict\n")
	fmt.Fprintf(&b, "ReadWritePaths=%s /proc/sys/net/ipv4/ip_forward\n", p.DataDir)
	b.WriteString("ProtectHome=true\n")
	b.WriteString("PrivateTmp=true\n")
	b.WriteString("ProtectKernelTunables=true\n")
	b.WriteString("ProtectKernelModules=true\n")
	b.WriteString("ProtectControlGroups=true\n")
	b.WriteString("ProtectClock=true\n")
	b.WriteString("ProtectHostname=true\n")
	b.WriteString("RestrictSUIDSGID=true\n")
	b.WriteString("RestrictRealtime=true\n")
	b.WriteString("LockPersonality=true\n")
	b.WriteString("MemoryDenyWriteExecute=true\n")
	b.WriteString("RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX AF_NETLINK\n")
	b.WriteString("SystemCallArchitectures=native\n\n")
	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=multi-user.target\n")
	return b.String()
}
