package install

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"strings"
	"time"

	"github.com/Sir-Adnan/wg-guard/internal/updatequeue"
)

const (
	UpdateBrokerServicePath = "/etc/systemd/system/wg-guard-update.service"
	UpdateBrokerPathPath    = "/etc/systemd/system/wg-guard-update.path"
	UpdateBrokerMarkerPath  = DataDir + "/update-broker.json"
	UpdateBrokerTimerPath   = "/etc/systemd/system/wg-guard-update.timer"
)

func RenderUpdateBrokerService() string {
	return `# Generated by wg-guard install
[Unit]
Description=WG-Guard verified update request runner
Documentation=https://github.com/Sir-Adnan/wg-guard
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/wg-guard update-request-run
TimeoutStartSec=45min
UMask=0077
`
}

func RenderUpdateBrokerTimer() string {
	return `# Generated by wg-guard install
[Unit]
Description=WG-Guard scheduled maintenance and inventory

[Timer]
OnBootSec=2min
OnUnitInactiveSec=1min
AccuracySec=5s
Unit=wg-guard-update.service

[Install]
WantedBy=timers.target
`
}

func RenderUpdateBrokerPath() string {
	return `# Generated by wg-guard install
[Unit]
Description=Watch for WG-Guard verified update requests
Documentation=https://github.com/Sir-Adnan/wg-guard

[Path]
PathExists=/var/lib/wg-guard/update-request.json
Unit=wg-guard-update.service
TriggerLimitIntervalSec=60
TriggerLimitBurst=3

[Install]
WantedBy=multi-user.target
`
}

type brokerSnapshot struct {
	path   string
	data   []byte
	mode   fs.FileMode
	exists bool
	remove bool
}

// EnsureUpdateBroker installs the fixed systemd path/oneshot bridge used by
// the Web Panel. The bridge executes only this verified binary's bounded
// update-request command; the panel never receives systemd or Docker access.
func EnsureUpdateBroker(ctx context.Context, h Host) error {
	return EnsureUpdateBrokerForContract(ctx, h, CurrentContract())
}

// Installed host code, rather than the caller's version, determines bridge
// capabilities. Rollback cannot leave a new timer invoking an old executable.
func EnsureUpdateBrokerForContract(ctx context.Context, h Host, contract Contract) error {
	if contract.MaintenanceProtocol != 0 && contract.MaintenanceProtocol != 2 {
		return terminalError("install.error.contract")
	}
	enhanced := contract.MaintenanceProtocol == 2
	if !h.IsRoot() {
		return fmt.Errorf("update broker: root is required")
	}
	if _, err := h.LookPath("systemctl"); err != nil {
		return fmt.Errorf("update broker: systemd is required: %w", err)
	}
	if err := h.MkdirAll(DataDir, 0o750); err != nil {
		return err
	}
	paths := updatequeue.New(DataDir).Paths()
	desired := []brokerSnapshot{
		{path: UpdateBrokerServicePath, data: []byte(RenderUpdateBrokerService()), mode: 0o644},
		{path: UpdateBrokerPathPath, data: []byte(RenderUpdateBrokerPath()), mode: 0o644},
		{path: paths.Marker, data: updatequeue.ReadyMarker(), mode: 0o600},
		{path: UpdateBrokerTimerPath, data: []byte(RenderUpdateBrokerTimer()), mode: 0o644},
	}
	previous := make([]brokerSnapshot, len(desired))
	if !enhanced {
		desired[2].data = []byte("{\"schema\":1}\n")
		desired[3].remove = true
	}
	for i, target := range desired {
		previous[i].path = target.path
		current, err := h.ReadFile(target.path)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}
		info, err := h.Stat(target.path)
		if err != nil || !info.Mode().IsRegular() {
			return fmt.Errorf("update broker: refusing non-regular artifact %s", target.path)
		}
		if target.path == paths.Marker {
			if !updatequeue.ValidReadyMarker(current) {
				return fmt.Errorf("update broker: refusing unowned marker %s", target.path)
			}
		} else if !strings.HasPrefix(string(current), "# Generated by wg-guard install\n") {
			return fmt.Errorf("update broker: refusing unowned unit %s", target.path)
		}
		previous[i].data, previous[i].mode, previous[i].exists = append([]byte(nil), current...), info.Mode().Perm(), true
	}
	if !previous[2].exists {
		for _, active := range []string{paths.Request, paths.Running} {
			if _, err := h.Stat(active); err == nil {
				return fmt.Errorf("update broker: refusing active request without an owned marker")
			} else if !errors.Is(err, fs.ErrNotExist) {
				return err
			}
		}
	}
	restore := func(disableNew bool) {
		if disableNew && !previous[1].exists {
			_ = h.Run(context.Background(), []string{"systemctl", "disable", "--now", "wg-guard-update.path"}, 30*time.Second)
			_ = h.Run(context.Background(), []string{"systemctl", "stop", "wg-guard-update.service"}, 30*time.Second)
		}
		if disableNew && !previous[3].exists {
			_ = h.Run(context.Background(), []string{"systemctl", "disable", "--now", "wg-guard-update.timer"}, 30*time.Second)
		}
		for _, old := range previous {
			if old.exists {
				_ = atomicWrite(h, old.path, old.data, old.mode)
			} else {
				_ = h.Remove(old.path)
			}
		}
		_ = h.Run(context.Background(), []string{"systemctl", "daemon-reload"}, 30*time.Second)
		if previous[3].exists {
			_ = h.Run(context.Background(), []string{"systemctl", "enable", "--now", "wg-guard-update.timer"}, 30*time.Second)
		}
	}
	for _, target := range desired {
		if target.remove {
			if previous[3].exists {
				if err := h.Run(ctx, []string{"systemctl", "disable", "--now", "wg-guard-update.timer"}, 30*time.Second); err != nil {
					restore(false)
					return err
				}
				if err := h.Remove(target.path); err != nil {
					restore(false)
					return err
				}
			}
			continue
		}
		if err := atomicWrite(h, target.path, target.data, target.mode); err != nil {
			restore(false)
			return err
		}
	}
	if err := h.Run(ctx, []string{"systemctl", "daemon-reload"}, 30*time.Second); err != nil {
		restore(false)
		return fmt.Errorf("update broker: daemon-reload: %w", err)
	}
	if err := h.Run(ctx, []string{"systemctl", "enable", "--now", "wg-guard-update.path"}, 30*time.Second); err != nil {
		restore(true)
		return fmt.Errorf("update broker: enable path: %w", err)
	}
	if enhanced {
		if err := h.Run(ctx, []string{"systemctl", "enable", "--now", "wg-guard-update.timer"}, 30*time.Second); err != nil {
			restore(true)
			return err
		}
	}
	return nil
}

type updateBrokerOwnership struct {
	service, path, marker, timer bool
}

func (o updateBrokerOwnership) present() bool  { return o.service || o.path || o.marker || o.timer }
func (o updateBrokerOwnership) hasUnits() bool { return o.service || o.path }

// inspectUpdateBroker recognizes only artifacts written by EnsureUpdateBroker.
// This keeps uninstall from claiming a foreign unit at a fixed system path.
func inspectUpdateBroker(h Host) (updateBrokerOwnership, error) {
	var owned updateBrokerOwnership
	for _, target := range []struct {
		path string
		set  *bool
	}{
		{UpdateBrokerServicePath, &owned.service},
		{UpdateBrokerPathPath, &owned.path},
		{UpdateBrokerTimerPath, &owned.timer},
	} {
		raw, err := h.ReadFile(target.path)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return owned, err
		}
		info, err := h.Stat(target.path)
		if err != nil || !info.Mode().IsRegular() || !strings.HasPrefix(string(raw), "# Generated by wg-guard install\n") {
			return owned, fmt.Errorf("update broker: refusing unowned unit %s", target.path)
		}
		*target.set = true
	}
	marker := updatequeue.New(DataDir).Paths().Marker
	raw, err := h.ReadFile(marker)
	if !errors.Is(err, fs.ErrNotExist) {
		if err != nil {
			return owned, err
		}
		info, statErr := h.Stat(marker)
		if statErr != nil || !info.Mode().IsRegular() || !updatequeue.ValidReadyMarker(raw) {
			return owned, fmt.Errorf("update broker: refusing unowned marker %s", marker)
		}
		owned.marker = true
	}
	return owned, nil
}

func updateBrokerArtifacts(owned updateBrokerOwnership) []string {
	if !owned.present() {
		return nil
	}
	paths := updatequeue.New(DataDir).Paths()
	result := []string{paths.Request, paths.Running, paths.Status}
	result = append(result, DataDir+"/update-scheduled.json", DataDir+"/update-history.json", DataDir+"/update-inventory.json")
	if owned.marker {
		result = append(result, paths.Marker)
	}
	if owned.service {
		result = append(result, UpdateBrokerServicePath)
	}
	if owned.path {
		result = append(result, UpdateBrokerPathPath)
	}
	if owned.timer {
		result = append(result, UpdateBrokerTimerPath)
	}
	return result
}

func stopUpdateBroker(ctx context.Context, h Host, owned updateBrokerOwnership) error {
	if owned.timer {
		if err := h.Run(ctx, []string{"systemctl", "disable", "--now", "wg-guard-update.timer"}, 30*time.Second); err != nil {
			return err
		}
	}
	if owned.path {
		if err := h.Run(ctx, []string{"systemctl", "disable", "--now", "wg-guard-update.path"}, 30*time.Second); err != nil {
			return fmt.Errorf("update broker: disable path: %w", err)
		}
	}
	if owned.service {
		if err := h.Run(ctx, []string{"systemctl", "stop", "wg-guard-update.service"}, 30*time.Second); err != nil {
			return fmt.Errorf("update broker: stop service: %w", err)
		}
	}
	return nil
}
